-- QTV04
CREATE OR ALTER PROC SP_UPDATE_LICHLAMVIEC
	@MANS INT,
	@NEWLLV TMPLICHLAMVIEC READONLY
AS
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	BEGIN TRY
		DELETE FROM LICHLAMVIEC
		WHERE MANS = @MANS

		--------------------------
		WAITFOR DELAY '0:0:05'
		--------------------------

		INSERT INTO LICHLAMVIEC (MANS, NGAYLAM, GIOBATDAU, GIOKETTHUC)
		SELECT MANS, NGAYLAM, CONVERT(TIME, GIOBATDAU) AS GIOBATDAU, CONVERT(TIME, GIOKETTHUC) AS GIOKETTHUC
		FROM @NEWLLV
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		IF CHARINDEX('CK_LICHLAMVIEC_GIOBATDAU', @ErrorMessage) > 0
		BEGIN
			RAISERROR('Giờ bắt đầu làm phải từ 8 giờ sáng!', 16, 1)
		END
		ELSE IF CHARINDEX('CK_LICHLAMVIEC_GIOKETTHUC', @ErrorMessage) > 0
		BEGIN
			RAISERROR('Giờ tan ca phải từ trước 20h!', 16, 1)
		END
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

--QTV03
CREATE OR ALTER PROC SP_GET_LLV_NHASI
	@MANS INT
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	SELECT NGAYLAM, DATEPART(HOUR, GIOBATDAU) BATDAU, DATEPART(HOUR, GIOKETTHUC) KETTHUC
	FROM LICHLAMVIEC
	WHERE MANS = @MANS
COMMIT TRAN
GO

