const {Router} = require('express')
const KHDTControllers = require('../controllers/KHDTControllers')
const { requirePermission, requireAuth } = require('../middleware/authMiddleware')

const router = Router()
router.get('/khdt', requireAuth, KHDTControllers.getKHDT)
router.post('/khdt', requireAuth, KHDTControllers.UpDateTrangThai)
router.get('/createKHDT', requirePermission(2), KHDTControllers.createKHDT1_get)
router.post('/createKHDT', requirePermission(2), KHDTControllers.createKHDT_post)
router.get('/khdt/init',requireAuth, KHDTControllers.KHDT_get_data)
router.get('/createKHDT/search/patients', requireAuth, KHDTControllers.search_hsbn_get)
router.get('/createKHDT/search/dentists', requireAuth, KHDTControllers.search_dentists_get)
router.get('/addDonThuoc', requirePermission(2), KHDTControllers.getAddDonThuoc)
router.post('/addDonThuoc', requirePermission(2), KHDTControllers.addDonThuoc)
router.get('/addDonThuoc/search/thuoc', requirePermission(2), KHDTControllers.search_thuoc_get)
module.exports = router;