CREATE OR ALTER PROC SP_POST_CREATE_HOADON
    @MAKH INT,
    @NGAYTT DATE,
    @NGUOITT NVARCHAR(255),
    @SOTIENNHAN INT,
    @LOAITT NVARCHAR(20),
    @NVTHANHTOAN INT,
	@LIST_MAKHDT dbo.LIST_MAKHDT READONLY
AS
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
BEGIN TRY
	UPDATE HSBN
	SET DATHANHTOAN = DATHANHTOAN + ISNULL(SumTONGTIEN, 0)
	FROM HOSOBN HSBN
	JOIN (
		SELECT MAHSBN, SUM(TONGTIEN) AS SumTONGTIEN
		FROM KHDIEUTRI KHDT
		JOIN @LIST_MAKHDT LIST ON KHDT.MAKHDIEUTRI = LIST.MAKHDT
		GROUP BY MAHSBN
	) AS Subquery
	ON HSBN.MAHSBN = Subquery.MAHSBN;

	--ĐỂ TEST
	WAITFOR DELAY '0:0:05'

	DECLARE @TONGTIENCANTT INT, @SOTIENTHOI INT

	SELECT @TONGTIENCANTT = SUM(KHDT.TONGTIEN) 
	FROM KHDIEUTRI KHDT
	WHERE KHDT.MAKHDIEUTRI IN (SELECT MAKHDT FROM @LIST_MAKHDT)

	SET @SOTIENTHOI = @SOTIENNHAN - @TONGTIENCANTT
	INSERT INTO HOADON(MAKH, NGAYTT, NGUOITT, TONGTIENCANTT, SOTIENNHAN, SOTIENTHOI, LOAITT, NVTHANHTOAN)
	VALUES (@MAKH, @NGAYTT, @NGUOITT, @TONGTIENCANTT, @SOTIENNHAN, @SOTIENTHOI, @LOAITT, @NVTHANHTOAN)
	
	DECLARE @MAHDTT INT = SCOPE_IDENTITY();

	UPDATE KHDIEUTRI
	SET MAHDTT = @MAHDTT
	FROM KHDIEUTRI JOIN @LIST_MAKHDT ON MAKHDIEUTRI = MAKHDT


END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0  
			ROLLBACK TRAN
	RAISERROR(N'Lỗi hệ thống', 16, 1)
	RETURN
END CATCH
COMMIT TRAN
GO

CREATE OR ALTER PROC SP_GET_DATATABLE_HSBN
	@FILTERQUERY NVARCHAR(MAX),
	@COLNAME NVARCHAR(MAX),
	@COLSORTORDER NVARCHAR(MAX),
	@OFFSET_START NVARCHAR(MAX),
	@LENGTH NVARCHAR(MAX)
AS
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN
	DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM HOSOBN '
	EXEC SP_EXECUTESQL @SQL
	
	SET @SQL = @SQL + @FILTERQUERY
	EXEC SP_EXECUTESQL @SQL

	SET @SQL = 'SELECT * FROM HOSOBN ' + @FILTERQUERY +
                    ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                    ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
	EXEC SP_EXECUTESQL @SQL
END
GO