DECLARE @FILTERQUERY NVARCHAR(MAX) = N'WHERE MAHSBN = 100007',
		@COLNAME NVARCHAR(MAX) = 'MAHSBN',
		@COLSORTORDER NVARCHAR(MAX) = 'ASC',
		@OFFSET_START NVARCHAR(MAX) = 0,
		@LENGTH NVARCHAR(MAX) = 10

EXEC SP_GET_DATATABLE_HSBN @FILTERQUERY, @COLNAME, @COLSORTORDER, @OFFSET_START, @LENGTH
