CREATE OR ALTER PROC SP_POST_ACCEPT_LICHHEN
    @MALH INT
AS
BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT 1 FROM LICHHEN WITH(UPDLOCK) WHERE MALH = @MALH AND XACNHAN = 0)
	BEGIN
	RAISERROR('Error', 16, 1);
	ROLLBACK TRAN
	RETURN
	END
	--test--
	WAITFOR DELAY '0:0:05'
	UPDATE LICHHEN
        SET
            XACNHAN = 1
        WHERE MALH = @MALH ;
	
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMessage NVARCHAR(4000);
		SET @ErrorMessage = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1);
		ROLLBACK TRAN
		RETURN
    END CATCH
COMMIT TRAN
--EXEC SP_POST_ACCEPT_LICHHEN 192221
GO
CREATE OR ALTER PROC SP_POST_DENY_LICHHEN
    @MALH INT
AS

BEGIN TRAN
	BEGIN TRY
	IF NOT EXISTS (SELECT 1 FROM LICHHEN WITH(UPDLOCK) WHERE MALH = @MALH AND XACNHAN = 0)
	BEGIN
	RAISERROR('Error', 16, 1);
	ROLLBACK TRAN
	RETURN
	END
	DELETE FROM LICHHEN
		WHERE MALH = @MALH 
	
	END TRY
	BEGIN CATCH
        DECLARE @ErrorMessage NVARCHAR(4000);
		SET @ErrorMessage = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1);
		ROLLBACK TRAN
		RETURN
    END CATCH
COMMIT TRAN

