CREATE OR ALTER PROC SP_CREATEKHDT
					@MAHSBN INT,
					@HOTENBN NVARCHAR(255),
					@MADIEUTRI INT,
					@MOTAKH NVARCHAR(255),
					@NGAYDIEUTRI DATE,
					@KHAMCHINH INT,
					@TENNSKHAMCHINH NVARCHAR(255),
					@TROKHAM INT = NULL,
					@TENNSTROKHAM NVARCHAR(255),
					@GHICHU NVARCHAR(255),
					@MAKHDIEUTRI INT OUTPUT
AS
	BEGIN TRY
		BEGIN TRAN
			SET TRANSACTION ISOLATION LEVEL READ COMMITTED
			DECLARE @MOTADT NVARCHAR(255)
			SET @MOTADT = (SELECT MOTA FROM DIEUTRI WHERE MADIEUTRI = @MADIEUTRI)
			INSERT INTO KHDIEUTRI VALUES(@MAHSBN,@HOTENBN,@MADIEUTRI,@MOTADT,@MOTAKH, @NGAYDIEUTRI, @KHAMCHINH,@TENNSKHAMCHINH, @TROKHAM,@TENNSTROKHAM, @GHICHU, 1, NULL, NULL)
			SET @MAKHDIEUTRI = SCOPE_IDENTITY()
			exec SP_SHOW_LOCK_IN_DB
			WAITFOR DELAY '00:00:05'
			IF @TROKHAM IS NOT NULL
				BEGIN
					IF @TROKHAM = @KHAMCHINH
						BEGIN
							RAISERROR('Nha sĩ khám chính không thể trùng với nha sĩ trợ khám!', 16, 1)
							RETURN
						END
				END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
	END CATCH
GO

CREATE OR ALTER PROC SP_GET_DATATABLE_KHDIEUTRI
	@FILTERQUERY NVARCHAR(MAX),
	@COLNAME NVARCHAR(MAX),
	@COLSORTORDER NVARCHAR(MAX),
	@OFFSET_START NVARCHAR(MAX),
	@LENGTH NVARCHAR(MAX),
	@MAKH INT
AS
BEGIN
	DECLARE @SQL1 NVARCHAR(MAX)
	DECLARE @SQL2 NVARCHAR(MAX)
	BEGIN TRAN
		SET TRANSACTION ISOLATION LEVEL READ COMMITTED
		IF (@MAKH IS NOT NULL)
		BEGIN
			SET @SQL1 = N'SELECT COUNT(*) recordsTotal FROM KHDIEUTRI KHDT JOIN HOSOBN HSBN ON KHDT.MAHSBN = HSBN.MAHSBN '
			SET @SQL2 = N'SELECT KHDT.MAKHDIEUTRI,
						KHDT.MAHSBN,
						KHDT.HOTENBN,
						KHDT.MOTADT,
						KHDT.NGAYDIEUTRI,
						KHDT.KHAMCHINH,
						KHDT.TENNSKHAMCHINH,
						KHDT.TROKHAM,
						KHDT.TENNSTROKHAM,
						CASE
							WHEN KHDT.TRANGTHAI = 1 THEN N''Đang điều trị''
							WHEN KHDT.TRANGTHAI = 2 THEN N''Đã hoàn thành''
							WHEN KHDT.TRANGTHAI = 3 THEN N''Đã hủy''
							ELSE N''không xác định''
						END AS TRANGTHAI, 
						CASE
							WHEN KHDT.MAHDTT IS NOT NULL THEN N''Đã trả tiền''
							ELSE N''Chưa trả tiền''
						END AS TRANGTHAI_TIEN,
						KHDT.MOTAKH, KHDT.GHICHU
						FROM KHDIEUTRI KHDT JOIN HOSOBN HSBN ON KHDT.MAHSBN = HSBN.MAHSBN'

		END
		ELSE
		BEGIN
			SET @SQL1 =  N'SELECT COUNT(*) recordsTotal FROM KHDIEUTRI KHDT '
			SET @SQL2 = N'SELECT KHDT.MAKHDIEUTRI,
						KHDT.MAHSBN,
						KHDT.HOTENBN,
						KHDT.MOTADT,
						KHDT.NGAYDIEUTRI,
						KHDT.KHAMCHINH,
						KHDT.TENNSKHAMCHINH,
						KHDT.TROKHAM,
						KHDT.TENNSTROKHAM,
						CASE
							WHEN KHDT.TRANGTHAI = 1 THEN N''Đang điều trị''
							WHEN KHDT.TRANGTHAI = 2 THEN N''Đã hoàn thành''
							WHEN KHDT.TRANGTHAI = 3 THEN N''Đã hủy''
							ELSE N''không xác định''
						END AS TRANGTHAI, 
						CASE
							WHEN KHDT.MAHDTT IS NOT NULL THEN N''Đã trả tiền''
							ELSE N''Chưa trả tiền''
						END AS TRANGTHAI_TIEN,
						KHDT.MOTAKH, KHDT.GHICHU
						FROM KHDIEUTRI KHDT'
		END
		EXEC SP_EXECUTESQL @SQL1
	
		SET @SQL1 = @SQL1 + @FILTERQUERY
		EXEC SP_EXECUTESQL @SQL1

		SET @SQL2 = @SQL2 + ' ' + @FILTERQUERY +
					' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
					' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';

		PRINT @SQL2
		EXEC SP_EXECUTESQL @SQL2
	COMMIT TRAN
END
GO