
CREATE OR ALTER PROC SP_GET_DATATABLE_HOADON
	@FILTERQUERY NVARCHAR(MAX),
	@COLNAME NVARCHAR(MAX),
	@COLSORTORDER NVARCHAR(MAX),
	@OFFSET_START NVARCHAR(MAX),
	@LENGTH NVARCHAR(MAX)
AS
BEGIN
BEGIN TRY
	DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM HOADON '
	EXEC SP_EXECUTESQL @SQL
	
	SET @SQL = @SQL + @FILTERQUERY
	EXEC SP_EXECUTESQL @SQL

	SET @SQL = 'SELECT * FROM HOADON ' + @FILTERQUERY +
                    ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                    ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
	EXEC SP_EXECUTESQL @SQL
END TRY
BEGIN CATCH
	DECLARE @ERROR_MESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
	RAISERROR(@ERROR_MESSAGE, 16, 1)
END CATCH
END
GO

CREATE OR ALTER PROC SP_GET_LIST_KH_KEYWORD
	@KEYWORD NVARCHAR(MAX)
AS
BEGIN
	SET @KEYWORD = @KEYWORD + '%'
	DECLARE @KEYWORD2 NVARCHAR(MAX) = '%' + @KEYWORD

	SELECT TOP 10 MAKH, HOTEN, SDT
	FROM KHACHHANG
	WHERE (CONVERT(NVARCHAR(MAX), MAKH) LIKE @KEYWORD OR
		   HOTEN LIKE @KEYWORD2 OR
		   SDT LIKE @KEYWORD)
END
GO

CREATE OR ALTER PROC SP_GET_LIST_KHDIEUTRI_THEO_MAKH
	@MAKH INT
AS
	SELECT MAKHDIEUTRI, TONGTIEN, NGAYDIEUTRI
	FROM KHDIEUTRI KHDT JOIN HOSOBN HSBN ON KHDT.MAHSBN = HSBN.MAHSBN 
	WHERE MAKH = @MAKH AND MAHDTT IS NULL AND TRANGTHAI != 3
GO

CREATE OR ALTER PROC SP_GET_LIST_KHDIEUTRI
AS
	SELECT MAKHDIEUTRI, TONGTIEN, NGAYDIEUTRI, MAHSBN
	FROM KHDIEUTRI WHERE MAHDTT IS NULL AND TRANGTHAI != 3
GO

--CREATE TYPE dbo.LIST_MAKHDT AS TABLE
--(
--    MAKHDT INT
--);
--GO

CREATE OR ALTER PROC SP_POST_CREATE_HOADON
    @MAKH INT,
    @NGAYTT DATE,
    @NGUOITT NVARCHAR(255),
    @SOTIENNHAN INT,
    @LOAITT NVARCHAR(20),
    @NVTHANHTOAN INT,
	@LIST_MAKHDT dbo.LIST_MAKHDT READONLY
AS
BEGIN TRAN
BEGIN TRY
	DECLARE @TONGTIENCANTT INT, @SOTIENTHOI INT

	SELECT @TONGTIENCANTT = SUM(KHDT.TONGTIEN) 
	FROM KHDIEUTRI KHDT
	WHERE KHDT.MAKHDIEUTRI IN (SELECT MAKHDT FROM @LIST_MAKHDT)

	SET @SOTIENTHOI = @SOTIENNHAN - @TONGTIENCANTT
	INSERT INTO HOADON(MAKH, NGAYTT, NGUOITT, TONGTIENCANTT, SOTIENNHAN, SOTIENTHOI, LOAITT, NVTHANHTOAN)
	VALUES (@MAKH, @NGAYTT, @NGUOITT, @TONGTIENCANTT, @SOTIENNHAN, @SOTIENTHOI, @LOAITT, @NVTHANHTOAN)
	
	DECLARE @MAHDTT INT = SCOPE_IDENTITY();

	UPDATE KHDIEUTRI
	SET MAHDTT = @MAHDTT
	FROM KHDIEUTRI JOIN @LIST_MAKHDT ON MAKHDIEUTRI = MAKHDT

	UPDATE HSBN
	SET DATHANHTOAN = DATHANHTOAN + ISNULL(SumTONGTIEN, 0)
	FROM HOSOBN HSBN
	JOIN (
		SELECT MAHSBN, SUM(TONGTIEN) AS SumTONGTIEN
		FROM KHDIEUTRI KHDT
		JOIN @LIST_MAKHDT LIST ON KHDT.MAKHDIEUTRI = LIST.MAKHDT
		GROUP BY MAHSBN
	) AS Subquery
	ON HSBN.MAHSBN = Subquery.MAHSBN;

END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0  
			ROLLBACK TRAN
	RAISERROR(N'Lỗi hệ thống', 16, 1)
	RETURN
END CATCH
COMMIT TRAN
GO