
CREATE OR ALTER PROC SP_GET_DATATABLE_HOADON
	@FILTERQUERY NVARCHAR(MAX),
	@COLNAME NVARCHAR(MAX),
	@COLSORTORDER NVARCHAR(MAX),
	@OFFSET_START NVARCHAR(MAX),
	@LENGTH NVARCHAR(MAX)
AS
BEGIN
BEGIN TRY
	DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM HOADON '
	EXEC SP_EXECUTESQL @SQL
	
	SET @SQL = @SQL + @FILTERQUERY
	EXEC SP_EXECUTESQL @SQL

	SET @SQL = 'SELECT * FROM HOADON ' + @FILTERQUERY +
                    ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                    ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
	EXEC SP_EXECUTESQL @SQL
END TRY
BEGIN CATCH
	DECLARE @ERROR_MESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
	RAISERROR(@ERROR_MESSAGE, 16, 1)
END CATCH
END
GO

CREATE OR ALTER PROC SP_GET_LIST_KH
AS
	SELECT MAKH, HOTEN FROM KHACHHANG
GO


CREATE OR ALTER PROC SP_GET_LIST_KHDIEUTRI_THEO_MAKH
	@MAKH INT
AS
	SELECT TOP 1000 MAKHDIEUTRI, TONGTIEN, NGAYDIEUTRI
	FROM KHDIEUTRI KHDT JOIN HOSOBN HSBN ON KHDT.MAHSBN = HSBN.MAHSBN 
	WHERE MAKH = @MAKH AND MAHDTT IS NULL AND TRANGTHAI != 3
GO

CREATE OR ALTER PROC SP_GET_LIST_KHDIEUTRI
AS
	SELECT TOP 1000 MAKHDIEUTRI, TONGTIEN, NGAYDIEUTRI, MAHSBN
	FROM KHDIEUTRI WHERE MAHDTT IS NULL AND TRANGTHAI != 3
GO

CREATE OR ALTER PROC SP_POST_CREATE_HOADON
	@MAKH INT,
	@NGAYTT DATE,
	@NGUOITT NVARCHAR(255),
	@TONGTIENCANTT INT,
	@SOTIENNHAN INT,
	@SOTIENTHOI INT,
	@LOAITT NVARCHAR(20),
	@NVTHANHTOAN INT,
	@MAHDTT INT OUTPUT
AS
BEGIN TRY
	INSERT INTO HOADON(MAKH, NGAYTT, NGUOITT, TONGTIENCANTT, SOTIENNHAN, SOTIENTHOI, LOAITT, NVTHANHTOAN)
	VALUES (@MAKH, @NGAYTT, @NGUOITT, @TONGTIENCANTT, @SOTIENNHAN, @SOTIENTHOI, @LOAITT, @NVTHANHTOAN)
	SET @MAHDTT = SCOPE_IDENTITY();
END TRY
BEGIN CATCH
	RAISERROR(N'Lỗi hệ thống', 16, 1)
END CATCH
GO

CREATE OR ALTER PROC SP_UPDATE_KHDT
	@MAKHDIEUTRI INT,
	@MAHDTT INT
AS
BEGIN TRY
	UPDATE KHDIEUTRI
	SET MAHDTT = @MAHDTT
	WHERE MAKHDIEUTRI = @MAKHDIEUTRI
END TRY
BEGIN CATCH
	RAISERROR(N'Lỗi hệ thống', 16, 1)
END CATCH
GO
