--CREATE NONCLUSTERED INDEX INDEX_KHDIEUTRI_MAHSBN
--ON KHDIEUTRI (MAHSBN ASC)
--DROP INDEX KHDIEUTRI.INDEX_KHDIEUTRI_MAHSBN
--SELECT HS.MAHSBN, HS.HOTENBN
--FROM KHDIEUTRI KH INNER JOIN HOSOBN HS ON KH.MAHSBN = HS.MAHSBN
--WHERE KH.MAHSBN = 1

CREATE INDEX INDEX_NHASI_MACN
ON NHASI (MACN)
DROP INDEX NHASI.INDEX_NHASI_MACN

CREATE NONCLUSTERED INDEX INMDEX_LICHHEN_NGAYHEN_GIOHEN
ON LICHHEN (NGAYHEN, GIOHEN)
INCLUDE (MANS, MAHSBN)