-- NHASI
CREATE INDEX IX_NHASI_MACN
ON NHASI (MACN) INCLUDE (MANS, HOTEN)
--DROP INDEX NHASI.IX_NHASI_MACN


-- LICHLAMVIEC
CREATE INDEX IX_LICHLAMVIEC_NGAYLAM_GIOBATDAU_GIOKETTHUC
ON LICHLAMVIEC (NGAYLAM, GIOBATDAU, GIOKETTHUC) INCLUDE (MANS)
DROP INDEX LICHLAMVIEC.IX_LICHLAMVIEC_NGAYLAM_GIOBATDAU_GIOKETTHUC


-- LICHNGHI
CREATE INDEX IX_LICHNGHI_NGAYNGHI
ON LICHNGHI (NGAYNGHI DESC)
DROP INDEX LICHNGHI.IX_LICHNGHI_NGAYNGHI


-- LICHHEN
CREATE CLUSTERED INDEX IX_LICHHEN_MANS_NGAYHEN_GIOHEN
ON LICHHEN (MANS, NGAYHEN DESC, GIOHEN ASC)

CREATE INDEX IX_LICHHEN_NGAYHEN_GIOHEN
ON LICHHEN (NGAYHEN DESC, GIOHEN ASC)
INCLUDE (MANS, MAHSBN)
DROP INDEX LICHHEN.IX_LICHHEN_NGAYHEN_GIOHEN

CREATE INDEX IX_LICHHEN_NGAYHEN_XACNHAN
ON LICHHEN (NGAYHEN DESC, XACNHAN)
DROP INDEX LICHHEN.IX_LICHHEN_NGAYHEN_XACNHAN


--CREATE NONCLUSTERED INDEX IX_LICHHEN_MAHSBN_XACNHAN_NGAYHEN 
--ON LICHHEN (MAHSBN, XACNHAN, NGAYHEN);
--DROP INDEX LICHHEN.IX_LICHHEN_MAHSBN_XACNHAN_NGAYHEN 


-- HOSOBN
CREATE INDEX IX_HOSOBN_MAKH
ON HOSOBN (MAKH)
--DROP INDEX HOSOBN.IX_HOSOBN_MAKH

CREATE INDEX IX_HOSOBN_SDTBN
ON HOSOBN (SDTBN)
DROP INDEX HOSOBN.IX_HOSOBN_SDTBN
