CREATE INDEX IX_KEHOACHDIEUTRI ON KHDIEUTRI(MAKHDIEUTRI, MAHSBN, KHAMCHINH, TROKHAM)
--DROP INDEX KHDIEUTRI.IX_KEHOACHDIEUTRI
--GO
CREATE INDEX IX_KEHOACHDIEUTRI_NGAY_TRANGTHAI ON KHDIEUTRI(NGAYDIEUTRI, TRANGTHAI) INCLUDE (MAKHDIEUTRI,MAHSBN,HOTENBN,MOTADT,KHAMCHINH,TENNSKHAMCHINH,TROKHAM,TENNSTROKHAM,MAHDTT,MOTAKH,GHICHU)
--DROP INDEX KHDIEUTRI.IX_KEHOACHDIEUTRI_NGAY_TRANGTHAI
--GO