--CREATE NONCLUSTERED INDEX INDEX_KHDIEUTRI_MAHSBN
--ON KHDIEUTRI (MAHSBN ASC)
--DROP INDEX KHDIEUTRI.INDEX_KHDIEUTRI_MAHSBN
--SELECT HS.MAHSBN, HS.HOTENBN
--FROM KHDIEUTRI KH INNER JOIN HOSOBN HS ON KH.MAHSBN = HS.MAHSBN
--WHERE KH.MAHSBN = 1

-- NHASI
CREATE INDEX IX_NHASI_MACN
ON NHASI (MACN) INCLUDE (MANS, HOTEN)
--DROP INDEX NHASI.IX_NHASI_MACN


-- LICHLAMVIEC
CREATE INDEX IX_LICHLAMVIEC_GIOBATDAU_GIOKETTHUC
ON LICHLAMVIEC (GIOBATDAU, GIOKETTHUC)
--DROP INDEX LICHLAMVIEC.IX_LICHLAMVIEC_GIOBATDAU_GIOKETTHUC

CREATE INDEX IX_LICHLAMVIEC_NGAYLAM_GIOBATDAU_GIOKETTHUC
ON LICHLAMVIEC (NGAYLAM, GIOBATDAU, GIOKETTHUC)
--DROP INDEX LICHLAMVIEC.IX_LICHLAMVIEC_NGAYLAM_GIOBATDAU_GIOKETTHUC


-- LICHNGHI
CREATE INDEX IX_LICHNGHI_NGAYNGHI
ON LICHNGHI (NGAYNGHI)
-- DROP INDEX LICHHEN.IX_LICHNGHI_NGAYNGHI


-- LICHHEN
CREATE INDEX IX_LICHHEN_NGAYHEN_GIOHEN
ON LICHHEN (NGAYHEN, GIOHEN)
INCLUDE (MANS, MAHSBN)
-- DROP INDEX LICHHEN.IX_LICHHEN_NGAYHEN_GIOHEN
