CREATE INDEX idx_MALH
ON LICHHEN (NGAYHEN, GIOHEN)
INCLUDE (MANS,MAHSBN);
--DROP INDEX idx_MALH ON LICHHEN;
CREATE INDEX idx_MACN
ON NHASI (MACN)
INCLUDE (HOTEN);
--DROP INDEX idx_MANS ON NHASI;
--exec SP_UPDATE_APPOINMENT 2, 2, 123, 10002, N'Vũ Minh Quỳnh', '0982168116', N'Trương Minh Thịnh', '2023-12-22', '18:00:00'
create index inx_ngayhen on LICHHEN(NGAYHEN) include (MALH,MANS,MAHSBN,HOTENBN, SDTBN, HOTENNS, GIOHEN, XACNHAN,MATAIKHAM)
create index inx_xacnhan on LICHHEN(XACNHAN) include (MALH,MANS,MAHSBN,HOTENBN, SDTBN, HOTENNS,NGAYHEN, GIOHEN, MATAIKHAM)
create index inx_xacngay on LICHHEN(XACNHAN,NGAYHEN) include (MALH,MANS,MAHSBN,HOTENBN, SDTBN, HOTENNS, GIOHEN, MATAIKHAM)
create index inx_hotenbn on LICHHEN(HOTENBN) include (MALH,MANS,MAHSBN, SDTBN, HOTENNS,NGAYHEN, GIOHEN,XACNHAN, MATAIKHAM)
create index inx_hotenns on LICHHEN(HOTENNS) include (MALH,MANS,MAHSBN,HOTENBN, SDTBN,NGAYHEN, GIOHEN,XACNHAN, MATAIKHAM)
