CREATE INDEX IX_KEHOACHDIEUTRI ON KHDIEUTRI(MAHSBN, KHAMCHINH, TROKHAM) INCLUDE (MAKHDIEUTRI,HOTENBN,MOTADT,TENNSKHAMCHINH,TENNSTROKHAM,MAHDTT,MOTAKH,GHICHU)
--DROP INDEX KHDIEUTRI.IX_KEHOACHDIEUTRI
GO


CREATE INDEX IX_KEHOACHDIEUTRI_NGAY_TRANGTHAI ON KHDIEUTRI(NGAYDIEUTRI, TRANGTHAI) INCLUDE (MAKHDIEUTRI,MAHSBN,HOTENBN,MOTADT,KHAMCHINH,TENNSKHAMCHINH,TROKHAM,TENNSTROKHAM,MAHDTT,MOTAKH,GHICHU)
--DROP INDEX KHDIEUTRI.IX_KEHOACHDIEUTRI_NGAY_TRANGTHAI
GO

CREATE INDEX IX_KEHOACHDIEUTRI_HOTENBN ON KHDIEUTRI(HOTENBN, NGAYDIEUTRI) INCLUDE (MAKHDIEUTRI,MAHSBN,MOTADT,KHAMCHINH,TENNSKHAMCHINH,TROKHAM,TENNSTROKHAM,MAHDTT,MOTAKH,GHICHU)
--DROP INDEX KHDIEUTRI.IX_KEHOACHDIEUTRI_NGAY_TRANGTHAI
GO