USE CSDLNC
GO


-- CREATE FILEGROUP
ALTER DATABASE CSDLNC
ADD FILEGROUP FG_BEFORE_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_BEFORE_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_BEFORE_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_BEFORE_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_JAN_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_JAN_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_JAN_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_JAN_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_FEB_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_FEB_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_FEB_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_FEB_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_MAR_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_MAR_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_MAR_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_MAR_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_APR_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_APR_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_APR_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_APR_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_MAY_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_MAY_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_MAY_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_MAY_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_JUN_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_JUN_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_JUN_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_JUN_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_JUL_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_JUL_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_JUL_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_JUL_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_AUG_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_AUG_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_AUG_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_AUG_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_SEP_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_SEP_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_SEP_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_SEP_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_OCT_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_OCT_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_OCT_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_OCT_2023

ALTER DATABASE CSDLNC
ADD FILEGROUP FG_NOV_2023

ALTER DATABASE CSDLNC
ADD FILE (
	NAME = CSDLNC_FG_NOV_2023,
	FILENAME = 'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CSDLNC_FG_NOV_2023',
	SIZE = 1MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 1
) TO FILEGROUP FG_NOV_2023


-- CREATE PARTITION FUNCTION
CREATE PARTITION FUNCTION YearPartitions(DATE)
AS RANGE RIGHT
FOR VALUES ('2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01', '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01', '2023-09-01', '2023-10-01', '2023-11-01', '2023-12-01')


-- CREATE PARTITION SCHEME
CREATE PARTITION SCHEME YearPartitionsScheme
AS PARTITION YearPartitions
TO (FG_BEFORE_2023, FG_JAN_2023, FG_FEB_2023, FG_MAR_2023, FG_APR_2023, FG_MAY_2023, FG_JUN_2023, FG_JUL_2023, FG_AUG_2023, FG_SEP_2023, FG_OCT_2023, FG_NOV_2023, [PRIMARY])

-- CREATE CLUSTERD INDEX ON PARTITION COLUMN

-- LICHHEN
ALTER TABLE LICHHEN
ADD PRIMARY KEY
NONCLUSTERED (MALH)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_LICHHEN_NGAYHEN
ON LICHHEN (NGAYHEN DESC)
ON YearPartitionsScheme(NGAYHEN)

--KHDIEUTRI
ALTER TABLE KHDIEUTRI
ADD PRIMARY KEY
NONCLUSTERED (MAKHDIEUTRI)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_KHDIEUTRI_NGAYDIEUTRI
ON KHDIEUTRI (NGAYDIEUTRI DESC)
ON YearPartitionsScheme(NGAYDIEUTRI)

--HOADON
ALTER TABLE HOADON
ADD PRIMARY KEY
NONCLUSTERED (MAHOADON)
ON [PRIMARY]

CREATE CLUSTERED INDEX IX_HOADON_NGAYTT
ON HOADON (NGAYTT DESC)
ON YearPartitionsScheme(NGAYTT)


--DROP INDEX LICHHEN.IX_LICHHEN_NGAYHEN

--CREATE CLUSTERED INDEX IX_TMP
--ON LICHHEN(MALH) ON [PRIMARY]

--DROP PARTITION SCHEME YearPartitionsScheme

--DROP PARTITION FUNCTION YearPartitions

--DROP INDEX LICHHEN.IX_TMP

--SELECT p.partition_number AS partition_number,
--f.name AS file_group,
--p.rows AS row_count
--FROM sys.partitions p JOIN sys.destination_data_spaces dds ON
--p.partition_number = dds.destination_id
--JOIN sys.filegroups f ON dds.data_space_id = f.data_space_id
--WHERE OBJECT_NAME(OBJECT_ID) = 'HOADON'
--order by partition_number;