USE MASTER

DECLARE @DB NVARCHAR(128)
SET @DB = 'CSDLNC'
IF (EXISTS 
    (SELECT name 
    FROM master.dbo.sysdatabases 
    WHERE ('[' + name + ']' = @DB OR name = @DB)))
BEGIN
    ALTER DATABASE CSDLNC SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE CSDLNC
END


CREATE DATABASE CSDLNC
GO
USE CSDLNC

CREATE TABLE KHACHHANG
(
  MAKH INT IDENTITY(1, 1) NOT NULL,
  HOTEN NVARCHAR(255) NOT NULL,
  SDT CHAR(10) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  MATKHAU VARCHAR(50) NOT NULL,
  PRIMARY KEY (MAKH),
  UNIQUE (SDT),
  UNIQUE (EMAIL), 
  CHECK (LEN(MATKHAU) >= 8)
);

CREATE TABLE HOSOBN
(
  MAHSBN INT IDENTITY(1, 1) NOT NULL,
  MAKH INT NULL,
  HOTENBN NVARCHAR(255) NOT NULL,
  NGAYSINH DATE NOT NULL,
  GIOITINH NVARCHAR(10) NOT NULL,
  SDTBN CHAR(10) NOT NULL,
  DIACHIBN NVARCHAR(255) NOT NULL,
  TONGTIENDIEUTRI INT NOT NULL,
  DATHANHTOAN INT NOT NULL,
  TTSUCKHOE NVARCHAR(255) NOT NULL,
  TTDIUNG NVARCHAR(255) NOT NULL,
  PRIMARY KEY (MAHSBN),
  FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
  CHECK (GIOITINH IN (N'Nam', N'Nữ')),
  CHECK (DATHANHTOAN >= 0),
  CHECK (TONGTIENDIEUTRI >= 0)
);

CREATE TABLE CHINHANH
(
  MACN INT IDENTITY(1, 1) NOT NULL,
  TENCN NVARCHAR(255) NOT NULL,
  DIACHICN NVARCHAR(255) NOT NULL,
  SDTCN CHAR(10) NOT NULL,
  PRIMARY KEY (MACN),
  UNIQUE (TENCN),
  UNIQUE (DIACHICN),
  UNIQUE (SDTCN)
);

CREATE TABLE THUOC
(
  MATHUOC INT IDENTITY(1, 1) NOT NULL,
  TENTHUOC NVARCHAR(255) NOT NULL,
  CONGDUNG NVARCHAR(255) NOT NULL,
  CHONGCHIDINH NVARCHAR(255) NOT NULL,
  TACDUNGPHU NVARCHAR(255) NOT NULL,
  HDSD NVARCHAR(255) NOT NULL,
  HSD DATE NOT NULL,
  NSX NVARCHAR(255) NOT NULL,
  DONGIA INT NOT NULL,
  SL INT NOT NULL,
  PRIMARY KEY (MATHUOC),
  UNIQUE (TENTHUOC),
  CHECK (DONGIA > 0),
  CHECK (SL >= 0)
);

CREATE TABLE NVNGHIEPVU
(
  MANV INT IDENTITY(1, 1) NOT NULL,
  HOTEN NVARCHAR(255) NOT NULL,
  NGAYSINH DATE NOT NULL,
  GIOITINH NVARCHAR(10) NOT NULL,
  SDT CHAR(10) NOT NULL,
  DIACHI NVARCHAR(255) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  LOAINV BIT NOT NULL,
  MATKHAU VARCHAR(50) NOT NULL,
  PRIMARY KEY (MANV),
  UNIQUE (SDT),
  UNIQUE (EMAIL),
  CHECK (GIOITINH IN (N'Nam', N'Nữ')),
  CHECK (LEN(MATKHAU) >= 8)
);

CREATE TABLE HOADON
(
  MAHOADON INT IDENTITY(1, 1) NOT NULL,
  MAKH INT NOT NULL,
  NGAYTT DATE NOT NULL,
  NGUOITT NVARCHAR(255) NOT NULL,
  TONGTIENCANTT INT NOT NULL,
  SOTIENNHAN INT NOT NULL,
  SOTIENTHOI INT NOT NULL,
  LOAITT NVARCHAR(20) NOT NULL,
  NVTHANHTOAN INT NOT NULL,
  PRIMARY KEY (MAHOADON),
  FOREIGN KEY (NVTHANHTOAN) REFERENCES NVNGHIEPVU(MANV),
  FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
  CHECK (SOTIENNHAN > 0),
  CHECK (SOTIENTHOI >= 0),
  CHECK (TONGTIENCANTT > 0),
  CHECK (LOAITT IN (N'Tiền mặt', N'Chuyển khoản', N'Ví điện tử')),
  CHECK (SOTIENNHAN >= TONGTIENCANTT),
  CHECK (SOTIENNHAN - SOTIENTHOI = TONGTIENCANTT),
  CHECK (DATEDIFF(DAY, GETDATE(), NGAYTT) < 0)
);

CREATE TABLE DIEUTRI
(
  MADIEUTRI INT IDENTITY(1, 1) NOT NULL,
  MOTA NVARCHAR(255) NOT NULL,
  PHIDIEUTRI INT NOT NULL,
  PRIMARY KEY (MADIEUTRI)
);

CREATE TABLE BEMATRANG
(
  MABEMATRANG INT IDENTITY(1, 1) NOT NULL,
  TENBEMATRANG NVARCHAR(255) NOT NULL,
  MOTA NVARCHAR(255) NOT NULL,
  PRIMARY KEY (MABEMATRANG),
  UNIQUE (TENBEMATRANG),
  CHECK (MABEMATRANG>= 1 AND MABEMATRANG <= 6)
);

CREATE TABLE RANG
(
  MARANG INT IDENTITY(1, 1) NOT NULL,
  TENRANG NVARCHAR(255) NOT NULL,
  MOTA NVARCHAR(255) NOT NULL,
  PRIMARY KEY (MARANG),
  UNIQUE (TENRANG)
);

CREATE TABLE NHASI
(
  MANS INT IDENTITY(1, 1) NOT NULL,
  HOTEN NVARCHAR(255) NOT NULL,
  NGAYSINH DATE NOT NULL,
  GIOITINH NVARCHAR(10) NOT NULL,
  SDT CHAR(10) NOT NULL,
  DIACHI NVARCHAR(255) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  MATKHAU VARCHAR(50) NOT NULL,
  MACN INT NOT NULL,
  PRIMARY KEY (MANS),
  FOREIGN KEY (MACN) REFERENCES CHINHANH(MACN),
  UNIQUE (SDT),
  UNIQUE (EMAIL),
  CHECK (GIOITINH IN (N'Nam', N'Nữ')),
  CHECK (LEN(MATKHAU) >= 8)
);

CREATE TABLE LICHLAMVIEC
(
  MANS INT NOT NULL,
  NGAYLAM INT NOT NULL,
  GIOBATDAU TIME NOT NULL,
  GIOKETTHUC TIME NOT NULL,
  PRIMARY KEY (MANS, NGAYLAM),
  FOREIGN KEY (MANS) REFERENCES NHASI(MANS),
  CHECK (GIOBATDAU < GIOKETTHUC),
  CHECK (GIOBATDAU >= CONVERT(TIME, '08:00:00')),
  CHECK (GIOKETTHUC <= CONVERT(TIME, '20:00:00')),
  CHECK (NGAYLAM IN (1, 2, 3, 4, 5, 6, 7))
);

CREATE TABLE KHDIEUTRI
(
  MAKHDIEUTRI INT IDENTITY(1, 1) NOT NULL,
  MAHSBN INT NOT NULL,
  HOTENBN NVARCHAR(255) NOT NULL,
  MADIEUTRI INT NOT NULL,
  MOTAKH NVARCHAR(255) NOT NULL,
  NGAYDIEUTRI DATE NOT NULL,
  KHAMCHINH INT NOT NULL,
  TENNSKHAMCHINH NVARCHAR(255) NOT NULL,
  TROKHAM INT NOT NULL,
  TENNSTROKHAM NVARCHAR(255) NOT NULL,
  GHICHU NVARCHAR(255) DEFAULT NULL,
  TRANGTHAI INT NOT NULL,
  MAHDTT INT NULL,
  TONGTIEN INT NULL,
  PRIMARY KEY (MAKHDIEUTRI),
  FOREIGN KEY (MAHSBN) REFERENCES HOSOBN(MAHSBN),
  FOREIGN KEY (MAHDTT) REFERENCES HOADON(MAHOADON),
  FOREIGN KEY (MADIEUTRI) REFERENCES DIEUTRI(MADIEUTRI),
  FOREIGN KEY (KHAMCHINH) REFERENCES NHASI(MANS),
  FOREIGN KEY (TROKHAM) REFERENCES NHASI(MANS),
  CHECK (TRANGTHAI IN (1, 2, 3)),
  CHECK (KHAMCHINH <> TROKHAM)
);

CREATE TABLE DONTHUOC
(
  MAKHDIEUTRI INT NOT NULL,
  NGAYKEDON DATE NOT NULL,
  TONGTIENTHUOC INT NOT NULL,
  GHICHU NVARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (MAKHDIEUTRI),
  FOREIGN KEY (MAKHDIEUTRI) REFERENCES KHDIEUTRI(MAKHDIEUTRI),
  CHECK (TONGTIENTHUOC > 0)
);

CREATE TABLE CHITIET_DONTHUOC
(
  MAKHDIEUTRI INT NOT NULL,
  MATHUOC INT NOT NULL,
  SOLUONG INT NOT NULL,
  DONGIATHUOC INT NOT NULL,
  PRIMARY KEY (MAKHDIEUTRI, MATHUOC),
  FOREIGN KEY (MATHUOC) REFERENCES THUOC(MATHUOC),
  FOREIGN KEY (MAKHDIEUTRI) REFERENCES DONTHUOC(MAKHDIEUTRI),
  CHECK (SOLUONG > 0),
  CHECK (DONGIATHUOC > 0)
);

CREATE TABLE RANGDIEUTRI
(
  MAKHDIEUTRI INT NOT NULL,
  MARANG INT NOT NULL,
  MABEMATRANG INT NOT NULL,
  PRIMARY KEY (MAKHDIEUTRI, MARANG, MABEMATRANG),
  FOREIGN KEY (MAKHDIEUTRI) REFERENCES KHDIEUTRI(MAKHDIEUTRI),
  FOREIGN KEY (MARANG) REFERENCES RANG(MARANG),
  FOREIGN KEY (MABEMATRANG) REFERENCES BEMATRANG(MABEMATRANG),
);

CREATE TABLE LICHHEN
(
  MALH INT IDENTITY(1, 1) NOT NULL,
  MANS INT NOT NULL,
  MAHSBN INT NOT NULL,
  HOTENBN NVARCHAR(255) NOT NULL,
  SDTBN CHAR(10) NOT NULL,
  HOTENNS NVARCHAR(255) NOT NULL,
  NGAYHEN DATE NOT NULL,
  GIOHEN TIME NOT NULL,
  XACNHAN INT NOT NULL,
  MATAIKHAM INT NULL,
  PRIMARY KEY (MALH),
  FOREIGN KEY (MANS) REFERENCES NHASI(MANS),
  FOREIGN KEY (MATAIKHAM) REFERENCES KHDIEUTRI(MAKHDIEUTRI),
  FOREIGN KEY (MAHSBN) REFERENCES HOSOBN(MAHSBN),
  CHECK (XACNHAN IN (0, 1)),
  UNIQUE (MANS, NGAYHEN, GIOHEN),
  UNIQUE (MAHSBN, NGAYHEN, GIOHEN)
);

CREATE TABLE LICHNGHI
(
  MANS INT NOT NULL,
  NGAYNGHI DATE NOT NULL,
  PRIMARY KEY (MANS, NGAYNGHI),
  FOREIGN KEY (MANS) REFERENCES NHASI(MANS),
);

USE MASTER