-- LOGIN
CREATE OR ALTER PROC SP_LOGIN_KHACHHANG
	@SDT CHAR(10),
	@MATKHAU VARCHAR(50),
	@LOAITK INT,
	@ID INT = NULL OUTPUT,
	@HOTEN NVARCHAR(255) = NULL OUTPUT,
	@LOAINV BIT = NULL OUTPUT
AS
BEGIN
	IF @LOAITK = 1
	BEGIN
		IF EXISTS (
			SELECT 1
			FROM KHACHHANG
			WHERE SDT = @SDT
		)
		BEGIN
			IF @MATKHAU = (
				SELECT MATKHAU
				FROM KHACHHANG
				WHERE SDT = @SDT
			)
			BEGIN
				SELECT @ID = MAKH, @HOTEN = HOTEN
				FROM KHACHHANG
				WHERE SDT = @SDT
				PRINT N'Đăng nhập thành công'
				SET @LOAINV = 0
				RETURN
			END
		END
	END
	ELSE IF @LOAITK = 2
	BEGIN
		IF EXISTS (
			SELECT 1
			FROM NHASI
			WHERE SDT = @SDT
		)
		BEGIN
			IF @MATKHAU = (
				SELECT MATKHAU
				FROM NHASI
				WHERE SDT = @SDT
			)
			BEGIN
				SELECT @ID = MANS, @HOTEN = HOTEN
				FROM NHASI
				WHERE SDT = @SDT
				PRINT N'Đăng nhập thành công'
				SET @LOAINV = 0
				RETURN
			END
		END
	END
	ELSE IF @LOAITK = 3
	BEGIN
		IF EXISTS (
			SELECT 1
			FROM NVNGHIEPVU
			WHERE SDT = @SDT
		)
		BEGIN
			IF @MATKHAU = (
				SELECT MATKHAU
				FROM NVNGHIEPVU
				WHERE SDT = @SDT
			)
			BEGIN
				SELECT @ID = MANV, @HOTEN = HOTEN, @LOAINV = LOAINV
				FROM NVNGHIEPVU
				WHERE SDT = @SDT
				PRINT N'Đăng nhập thành công'
				RETURN
			END
		END
	END
	BEGIN
		RAISERROR('Số điện thoại hoặc mật khẩu không chính xác', 16, 1)
	END
END
GO

-- REGISTER
CREATE OR ALTER PROC SP_REGISTER_KHACHHANG
	@HOTEN NVARCHAR(255),
	@SDT CHAR(10),
	@EMAIL VARCHAR(50),
	@MATKHAU VARCHAR(50)
AS
BEGIN
	IF LEN(@MATKHAU) < 8
	BEGIN
		RAISERROR('Mật khẩu phải dài tối thiếu 8 kí tự', 16, 1)
		RETURN
	END
	BEGIN TRY
		INSERT INTO KHACHHANG VALUES(@HOTEN, @SDT, @EMAIL, @MATKHAU)
	END TRY
	BEGIN CATCH
		RAISERROR('Số điện thoại đã được đăng ký', 16, 1)
	END CATCH
END
GO

SELECT TOP 5 *
FROM KHACHHANG
ORDER BY MAKH DESC