-- SP_GET_DATATABLE_NV
CREATE OR ALTER PROC SP_GET_DATATABLE_NV
    @FILTERQUERY NVARCHAR(MAX),
    @COLNAME NVARCHAR(MAX),
    @COLSORTORDER NVARCHAR(MAX),
    @OFFSET_START NVARCHAR(MAX),
    @LENGTH NVARCHAR(MAX)
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM NVNGHIEPVU '
    EXEC SP_EXECUTESQL @SQL
    
    SET @SQL = @SQL + @FILTERQUERY
    EXEC SP_EXECUTESQL @SQL
    SET @SQL = 'SELECT * FROM NVNGHIEPVU ' + @FILTERQUERY +
                ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
    EXEC SP_EXECUTESQL @SQL
END
GO

CREATE OR ALTER PROC SP_CREATE_NV
    @HOTEN NVARCHAR(255),
    @NGAYSINH DATE,
    @GIOITINH NVARCHAR(10),
	@SDT CHAR(10),
    @DIACHI NVARCHAR(255),
    @EMAIL VARCHAR(255),
    @LOAINV BIT,
    @MATKHAU NVARCHAR(255)
AS
BEGIN TRAN
	IF len(@MATKHAU) < 8
	BEGIN
		RAISERROR(N'Mật khẩu phải ít nhất 8 kí tự!', 16, 1)
		ROLLBACK TRAN
		RETURN
	END
    BEGIN TRY
        INSERT INTO NVNGHIEPVU VALUES(@HOTEN, @NGAYSINH, @GIOITINH, @SDT, @DIACHI, @EMAIL, @LOAINV, @MATKHAU)
    END TRY
    BEGIN CATCH
		ROLLBACK TRAN
        RAISERROR('Số điện thoại hoặc mật khẩu đã được đăng ký!', 16, 1)
    END CATCH
COMMIT TRAN
GO

-- UPDATE NHANVIEN
CREATE OR ALTER PROC SP_UPDATE_NHANVIEN
	@MANV INT,
	@HOTEN NVARCHAR(255),
	@NGAYSINH DATE,
    @GIOITINH NVARCHAR(10),	
    @DIACHI NVARCHAR(255),
	@LOAINV BIT
AS
BEGIN TRAN
	BEGIN TRY
		UPDATE NVNGHIEPVU
		SET
			HOTEN = @HOTEN,
			NGAYSINH = @NGAYSINH,
            GIOITINH = @GIOITINH,
			DIACHI = @DIACHI,
			LOAINV = @LOAINV
		WHERE MANV = @MANV
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1)
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

--data NS
CREATE OR ALTER PROC SP_GET_DATATABLE_NS
    @FILTERQUERY NVARCHAR(MAX),
    @COLNAME NVARCHAR(MAX),
    @COLSORTORDER NVARCHAR(MAX),
    @OFFSET_START NVARCHAR(MAX),
    @LENGTH NVARCHAR(MAX)
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM NHASI '
    EXEC SP_EXECUTESQL @SQL
    
    SET @SQL = @SQL + @FILTERQUERY
    EXEC SP_EXECUTESQL @SQL

    SET @SQL = 'SELECT * FROM NHASI ' + @FILTERQUERY +
                ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
    EXEC SP_EXECUTESQL @SQL
END
GO

-- TAO NS
CREATE PROC SP_CREATE_NS
    @HOTEN NVARCHAR(255),
    @NGAYSINH DATE,
    @GIOITINH NVARCHAR(10),
    @SDT CHAR(10),
    @DIACHI NVARCHAR(255),
    @EMAIL VARCHAR(255),
    @MACN INT,
    @MATKHAU VARCHAR(50)
AS
BEGIN TRAN
	IF LEN(@MATKHAU) < 8
	BEGIN
		RAISERROR(N'Mật khẩu phải ít nhất 8 kí tự!', 16, 1)
		ROLLBACK TRAN
		RETURN
	END
	
    BEGIN TRY
        INSERT INTO NHASI VALUES(@HOTEN, @NGAYSINH, @GIOITINH, @SDT, @DIACHI, @EMAIL, @MACN, @MATKHAU)
	END TRY
	BEGIN CATCH
		RAISERROR(N'Số điện thoại hoặc Email đã được đăng ký', 16, 1)
		ROLLBACK TRAN
	END CATCH
COMMIT TRAN
GO

SELECT * FROM NHASI

-- UPDATE NHASI
CREATE OR ALTER PROC SP_UPDATE_NHASI
	@MANS INT,
	@HOTEN NVARCHAR(255),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(10),
	@DIACHI NVARCHAR(255)
AS
BEGIN
	BEGIN TRY
		UPDATE NHASI
		SET
			HOTEN = @HOTEN,
			NGAYSINH = @NGAYSINH,
			GIOITINH = @GIOITINH,
			DIACHI = @DIACHI
		WHERE MANS = @MANS

	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1)
	END CATCH
END
GO
