-- SP_GET_DATATABLE_NV
CREATE OR ALTER PROC SP_GET_DATATABLE_NV
    @FILTERQUERY NVARCHAR(MAX),
    @COLNAME NVARCHAR(MAX),
    @COLSORTORDER NVARCHAR(MAX),
    @OFFSET_START NVARCHAR(MAX),
    @LENGTH NVARCHAR(MAX)
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM NVNGHIEPVU '
    EXEC SP_EXECUTESQL @SQL
    
    SET @SQL = @SQL + @FILTERQUERY
    EXEC SP_EXECUTESQL @SQL

    SET @SQL = 'SELECT * FROM NVNGHIEPVU ' + @FILTERQUERY +
                ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
    EXEC SP_EXECUTESQL @SQL
END
GO

CREATE OR ALTER PROC SP_CREATE_NV
    @HOTEN NVARCHAR(255),
    @NGAYSINH DATE,
    @GIOITINH NVARCHAR(10),
	@SDT CHAR(10),
    @DIACHI NVARCHAR(255),
    @EMAIL NVARCHAR(255),
    @LOAINV BIT,
    @MATKHAU NVARCHAR(255)
AS
BEGIN
    BEGIN TRY
        INSERT INTO NVNGHIEPVU VALUES(@HOTEN, @NGAYSINH, @GIOITINH, @SDT, @, @EMAIL, @LOAINV, @MATKHAU)
    END TRY
    BEGIN CATCH
        RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
    END CATCH
END
GO

-- UPDATE NHANVIEN
CREATE OR ALTER PROC SP_UPDATE_NHANVIEN
	@MANV INT,
	@HOTEN NVARCHAR(255),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(10),
	@DIACHI NVARCHAR(255),
	@SDT CHAR(10),
	@EMAIL NVARCHAR(255),
	@LOAINV BIT,
	@MATKHAU NVARCHAR(255)
AS
BEGIN
	BEGIN TRY
		UPDATE NVNGHIEPVU
		SET
			HOTEN = @HOTEN,
			NGAYSINH = @NGAYSINH,
			GIOITINH = @GIOITINH,
			DIACHI = @DIACHI,
			SDT = @SDT,
			EMAIL = @EMAIL,
			LOAINV = @LOAINV,
			MATKHAU = @MATKHAU
		WHERE MANV = @MANV
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1)
	END CATCH
END
GO

--data NS
CREATE OR ALTER PROC SP_GET_DATATABLE_NS
    @FILTERQUERY NVARCHAR(MAX),
    @COLNAME NVARCHAR(MAX),
    @COLSORTORDER NVARCHAR(MAX),
    @OFFSET_START NVARCHAR(MAX),
    @LENGTH NVARCHAR(MAX)
AS
BEGIN
    DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM NHASI '
    EXEC SP_EXECUTESQL @SQL
    
    SET @SQL = @SQL + @FILTERQUERY
    EXEC SP_EXECUTESQL @SQL

    SET @SQL = 'SELECT * FROM NHASI ' + @FILTERQUERY +
                ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
    EXEC SP_EXECUTESQL @SQL
END
GO
-- TAO NS
CREATE OR ALTER PROC SP_CREATE_NS
    @HOTEN NVARCHAR(255),
    @NGAYSINH DATE,
    @GIOITINH NVARCHAR(10),
    @DIACHI NVARCHAR(255),
    @SDT CHAR(10),
    @EMAIL NVARCHAR(255),
    @MACN INT,
    @MATKHAU NVARCHAR(255)
AS
BEGIN
    BEGIN TRY
        INSERT INTO NHASI VALUES(@HOTEN, @NGAYSINH, @GIOITINH, @DIACHI, @SDT, @EMAIL, @MACN, @MATKHAU)
    END TRY
    BEGIN CATCH
        RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
    END CATCH
END
GO

-- UPDATE NHASI
CREATE OR ALTER PROC SP_UPDATE_NHASI
	@MANS INT,
	@HOTEN NVARCHAR(255),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(10),
	@DIACHI NVARCHAR(255),
	@SDT CHAR(10),
	@EMAIL NVARCHAR(255),
	@MACN INT,
	@MATKHAU NVARCHAR(255)
AS
BEGIN
	BEGIN TRY
		UPDATE NHASI
		SET
			HOTEN = @HOTEN,
			NGAYSINH = @NGAYSINH,
			GIOITINH = @GIOITINH,
			DIACHI = @DIACHI,
			SDT = @SDT,
			EMAIL = @EMAIL,
			MACN = @MACN,
			MATKHAU = @MATKHAU
		WHERE MANS = @MANS
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1)
	END CATCH
END
GO

