--CREATE TYPE THUOCARRAY AS TABLE
--(
--	MATHUOC INT,
--	SOLUONG INT
--)
--go

CREATE OR ALTER PROC SP_CREATEKHDT
					@MAHSBN INT,
					@HOTENBN NVARCHAR(255),
					@MADIEUTRI INT,
					@MOTAKH NVARCHAR(255),
					@NGAYDIEUTRI DATE,
					@KHAMCHINH INT,
					@TENNSKHAMCHINH NVARCHAR(255),
					@TROKHAM INT = NULL,
					@TENNSTROKHAM NVARCHAR(255),
					@GHICHU NVARCHAR(255),
					@MAKHDIEUTRI INT OUTPUT
AS
	BEGIN TRY
		IF @TROKHAM IS NOT NULL
			BEGIN
				IF @TROKHAM = @KHAMCHINH
					BEGIN
						RAISERROR('Nha sĩ khám chính không thể trùng với nha sĩ trợ khám!', 16, 1)
						RETURN
					END
			END
		BEGIN TRAN
			DECLARE @MOTADT NVARCHAR(255)
			SET @MOTADT = (SELECT MOTA FROM DIEUTRI WHERE MADIEUTRI = @MADIEUTRI)
			INSERT INTO KHDIEUTRI VALUES(@MAHSBN,@HOTENBN,@MADIEUTRI,@MOTADT,@MOTAKH, @NGAYDIEUTRI, @KHAMCHINH,@TENNSKHAMCHINH, @TROKHAM,@TENNSTROKHAM, @GHICHU, 1, NULL, NULL)
			SET @MAKHDIEUTRI = SCOPE_IDENTITY()
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
	END CATCH
GO
CREATE OR ALTER PROC SP_CREATERANGDIEUTRI
					@MAKHDIEUTRI INT,
					@MARANG INT,
					@MABEMATRANG INT
AS
	BEGIN
		BEGIN TRY
			INSERT INTO RANGDIEUTRI VALUES(@MAKHDIEUTRI, @MARANG, @MABEMATRANG)
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END

go


CREATE OR ALTER PROC SP_GET_DATATABLE_KHDIEUTRI
	@FILTERQUERY NVARCHAR(MAX),
	@COLNAME NVARCHAR(MAX),
	@COLSORTORDER NVARCHAR(MAX),
	@OFFSET_START NVARCHAR(MAX),
	@LENGTH NVARCHAR(MAX),
	@MAKH INT
AS
BEGIN
	DECLARE @SQL1 NVARCHAR(MAX)
	DECLARE @SQL2 NVARCHAR(MAX)
	IF (@MAKH IS NOT NULL)
	BEGIN
		SET @SQL1 = N'SELECT COUNT(*) recordsTotal FROM KHDIEUTRI KHDT JOIN HOSOBN HSBN ON KHDT.MAHSBN = HSBN.MAHSBN '
		SET @SQL2 = N'SELECT KHDT.MAKHDIEUTRI,
					KHDT.MAHSBN,
					KHDT.HOTENBN,
					KHDT.MOTADT,
					KHDT.NGAYDIEUTRI,
					KHDT.KHAMCHINH,
					KHDT.TENNSKHAMCHINH,
					KHDT.TROKHAM,
					KHDT.TENNSTROKHAM,
					CASE
						WHEN KHDT.TRANGTHAI = 1 THEN N''Đang điều trị''
						WHEN KHDT.TRANGTHAI = 2 THEN N''Đã hoàn thành''
						WHEN KHDT.TRANGTHAI = 3 THEN N''Đã hủy''
						ELSE N''không xác định''
					END AS TRANGTHAI, 
					CASE
						WHEN KHDT.MAHDTT IS NOT NULL THEN N''Đã trả tiền''
						ELSE N''Chưa trả tiền''
					END AS TRANGTHAI_TIEN,
					KHDT.MOTAKH, KHDT.GHICHU
					FROM KHDIEUTRI KHDT JOIN HOSOBN HSBN ON KHDT.MAHSBN = HSBN.MAHSBN'

	END
	ELSE
	BEGIN
		SET @SQL1 =  N'SELECT COUNT(*) recordsTotal FROM KHDIEUTRI KHDT '
		SET @SQL2 = N'SELECT KHDT.MAKHDIEUTRI,
					KHDT.MAHSBN,
					KHDT.HOTENBN,
					KHDT.MOTADT,
					KHDT.NGAYDIEUTRI,
					KHDT.KHAMCHINH,
					KHDT.TENNSKHAMCHINH,
					KHDT.TROKHAM,
					KHDT.TENNSTROKHAM,
					CASE
						WHEN KHDT.TRANGTHAI = 1 THEN N''Đang điều trị''
						WHEN KHDT.TRANGTHAI = 2 THEN N''Đã hoàn thành''
						WHEN KHDT.TRANGTHAI = 3 THEN N''Đã hủy''
						ELSE N''không xác định''
					END AS TRANGTHAI, 
					CASE
						WHEN KHDT.MAHDTT IS NOT NULL THEN N''Đã trả tiền''
						ELSE N''Chưa trả tiền''
					END AS TRANGTHAI_TIEN,
					KHDT.MOTAKH, KHDT.GHICHU
					FROM KHDIEUTRI KHDT'
	END
	EXEC SP_EXECUTESQL @SQL1
	
	SET @SQL1 = @SQL1 + @FILTERQUERY
	EXEC SP_EXECUTESQL @SQL1

    SET @SQL2 = @SQL2 + ' ' + @FILTERQUERY +
                ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';

    PRINT @SQL2
	EXEC SP_EXECUTESQL @SQL2
END
GO

CREATE OR ALTER PROC SP_UPDATETRANGTHAI
					@TRANGTHAI INT,
					@MAKHDIEUTRI INT
AS
	BEGIN
		BEGIN TRY
			UPDATE KHDIEUTRI
			SET TRANGTHAI = @TRANGTHAI
			WHERE MAKHDIEUTRI = @MAKHDIEUTRI
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END
GO

CREATE OR ALTER PROC SP_SEARCH_DENTISTS_KEYWORD
	@KEYWORD NVARCHAR(MAX)
AS
BEGIN
	SET @KEYWORD = @KEYWORD + '%'
	DECLARE @KEYWORD2 NVARCHAR(MAX) = '%' + @KEYWORD
	SELECT TOP 10 MANS, HOTEN
	FROM NHASI
	WHERE
		CONVERT(NVARCHAR(MAX), MANS) LIKE @KEYWORD OR
		HOTEN LIKE @KEYWORD2
	RETURN
END
GO


CREATE OR ALTER   PROC SP_XEM_DON_THUOC
	@MAKHDIEUTRI INT
AS
BEGIN
	BEGIN TRY
		SELECT T.TENTHUOC, CT.SOLUONG, CT.DONGIATHUOC FROM CHITIET_DONTHUOC CT JOIN THUOC T ON CT.MATHUOC = T.MATHUOC WHERE @MAKHDIEUTRI = MAKHDIEUTRI
	END TRY
	BEGIN CATCH
		RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
	END CATCH
END
GO



CREATE OR ALTER   PROC SP_XEM_RANG_DIEU_TRI
	@MAKHDIEUTRI INT
AS
BEGIN
	BEGIN TRY
		SELECT RANG.TENRANG, BEMATRANG.TENBEMATRANG FROM RANGDIEUTRI JOIN RANG ON RANGDIEUTRI.MARANG = RANG.MARANG JOIN BEMATRANG ON RANGDIEUTRI.MABEMATRANG = BEMATRANG.MABEMATRANG WHERE RANGDIEUTRI.MAKHDIEUTRI = @MAKHDIEUTRI
	END TRY
	BEGIN CATCH
		RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
	END CATCH
END
GO


CREATE OR ALTER PROC SP_ADD_CHI_TIET_DON_THUOC
	@MAKHDIEUTRI INT,
	@GHICHU NVARCHAR(255),
	@MANGTHUOC THUOCARRAY READONLY
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
		IF (EXISTS (SELECT 1 FROM @MANGTHUOC MT JOIN THUOC T ON MT.MATHUOC = T.MATHUOC WHERE MT.SOLUONG > T.SL))
		BEGIN
			RAISERROR('Số lượng để kê đơn vượt qua số còn lại trong kho!', 16, 1)
			RETURN
		END
        IF EXISTS (SELECT 1 FROM DONTHUOC WHERE MAKHDIEUTRI = @MAKHDIEUTRI) OR EXISTS (SELECT 1 FROM CHITIET_DONTHUOC WHERE MAKHDIEUTRI = @MAKHDIEUTRI)		
		BEGIN
			RAISERROR('Kế hoạch điều trị này đã được kê đơn thuốc và không thể tạo thêm!', 16, 1)
			RETURN
		END

			EXEC SP_ADD_DON_THUOC @MAKHDIEUTRI,@GHICHU
			INSERT INTO CHITIET_DONTHUOC (MAKHDIEUTRI, MATHUOC, SOLUONG, DONGIATHUOC)
			SELECT @MAKHDIEUTRI, M.MATHUOC, M.SOLUONG, THUOC.DONGIA
			FROM @MANGTHUOC AS M
			JOIN THUOC ON M.MATHUOC = THUOC.MATHUOC;
        
			UPDATE THUOC
			SET SL = SL - M.SOLUONG
			FROM @MANGTHUOC AS M
			JOIN THUOC ON M.MATHUOC = THUOC.MATHUOC;

			EXEC SP_UPDATEDONTHUOC @MAKHDIEUTRI

			EXEC SP_UPDATETRANGTHAI 2,@MAKHDIEUTRI

			UPDATE KHDIEUTRI
			SET TONGTIEN = (SELECT TONGTIENTHUOC FROM DONTHUOC WHERE @MAKHDIEUTRI = MAKHDIEUTRI)
			WHERE @MAKHDIEUTRI = MAKHDIEUTRI

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;

		SELECT @ErrorMessage = ERROR_MESSAGE(), 
			   @ErrorSeverity = ERROR_SEVERITY(),
			   @ErrorState = ERROR_STATE();
		RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
END
GO



CREATE OR ALTER  PROC SP_UPDATEDONTHUOC
					@MAKHDIEUTRI INT
AS
	BEGIN
		BEGIN TRY
			UPDATE DONTHUOC
			SET TONGTIENTHUOC = (SELECT SUM(SOLUONG*DONGIATHUOC) FROM CHITIET_DONTHUOC CT WHERE CT.MAKHDIEUTRI = @MAKHDIEUTRI)
			WHERE DONTHUOC.MAKHDIEUTRI = @MAKHDIEUTRI
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END
GO

CREATE OR ALTER  PROC SP_SEARCH_THUOC_KEYWORD
	@KEYWORD NVARCHAR(MAX)
AS
BEGIN
	SET @KEYWORD = @KEYWORD + '%'
	DECLARE @KEYWORD2 NVARCHAR(MAX) = '%' + @KEYWORD
	SELECT TOP 10 MATHUOC, TENTHUOC
	FROM THUOC
	WHERE
		CONVERT(NVARCHAR(MAX), MATHUOC) LIKE @KEYWORD OR
		TENTHUOC LIKE @KEYWORD2
	RETURN
END
GO

CREATE OR ALTER   PROC SP_ADD_DON_THUOC
	@MAKHDIEUTRI INT,
	@GHICHU NVARCHAR(255)
AS
BEGIN
	BEGIN TRY
		INSERT INTO DONTHUOC VALUES(@MAKHDIEUTRI,GETDATE(),1,@GHICHU)
	END TRY
	BEGIN CATCH
		RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
	END CATCH
END
Go

CREATE OR ALTER PROC SP_GETDIEUTRI
AS
	SELECT MADIEUTRI, MOTA FROM DIEUTRI
GO

