use CSDLNC
CREATE OR ALTER PROC SP_GETKHDT
					 @MAKH INT = NULL
AS
	BEGIN
		IF @MAKH IS NULL
			BEGIN
				SELECT 
					KHDT.MAKHDIEUTRI,
					HSBN.HOTENBN,
					DT.MOTA,
					KHDT.MOTAKH,
					KHDT.NGAYDIEUTRI,
					NS1.HOTEN AS KHAMCHINH,
					NS2.HOTEN AS KHAMPHU,
					KHDT.GHICHU,
					CASE
						WHEN KHDT.MAHDTT IS NOT NULL THEN N'Đã trả tiền'
						ELSE N'Chưa trả tiền'
					END AS TRANGTHAI_TIEN,
					CASE
						WHEN KHDT.TRANGTHAI = 1 THEN N'Đang điều trị'
						WHEN KHDT.TRANGTHAI = 2 THEN N'Đã hoàn thành'
						WHEN KHDT.TRANGTHAI = 3 THEN N'Đã hủy'
						ELSE 'không xác định'
					END AS TRANGTHAI
				FROM 
					KHDIEUTRI KHDT
				JOIN 
					HOSOBN HSBN ON KHDT.MAHSBN = HSBN.MAHSBN
				JOIN 
					DIEUTRI DT ON DT.MADIEUTRI = KHDT.MADIEUTRI
				JOIN 
					NHASI NS1 ON KHDT.KHAMCHINH = NS1.MANS
				JOIN 
					NHASI NS2 ON NS2.MANS = KHDT.TROKHAM;
			END
		ELSE
			BEGIN
				SELECT * FROM KHDIEUTRI WHERE @MAKH = MAKHDIEUTRI
			END
	END
GO
CREATE OR ALTER PROC SP_GETKHDTBASEDONMAHSBN
					 @MAHSBN INT = NULL
AS
	IF @MAHSBN IS NOT NULL
		BEGIN
			SELECT * FROM KHDIEUTRI WHERE @MAHSBN = MAHSBN
		END
GO
CREATE OR ALTER PROC SP_GETDIEUTRI
AS
	SELECT MADIEUTRI, MOTA FROM DIEUTRI
GO

CREATE OR ALTER PROC SP_GETNHASI
AS
	SELECT MANS, HOTEN FROM NHASI
GO


CREATE OR ALTER PROC SP_LISTHSBN
AS
	SELECT * FROM HOSOBN
GO


CREATE OR ALTER PROC SP_CREATEKHDT
					@MAHSBN INT,
					@MADIEUTRI INT,
					@MOTAKH NVARCHAR(255),
					@NGAYDIEUTRI DATE,
					@KHAMCHINH INT,
					@TROKHAM INT = NULL,
					@GHICHU NVARCHAR(255)
AS
	BEGIN
		IF @TROKHAM IS NOT NULL
			BEGIN
				IF @TROKHAM = @KHAMCHINH
					BEGIN
						RAISERROR('Nha sĩ khám chính không thể trùng với nha sĩ trợ khám!', 16, 1)
						RETURN
					END
			END
		BEGIN TRY
			INSERT INTO KHDIEUTRI VALUES(@MAHSBN,@MADIEUTRI,@MOTAKH, @NGAYDIEUTRI, @KHAMCHINH, @TROKHAM, @GHICHU, 1, NULL)
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END

CREATE OR ALTER PROC SP_CREATEKHDT
					@MAHSBN INT,
					@MADIEUTRI INT,
					@MOTAKH NVARCHAR(255),
					@NGAYDIEUTRI DATE,
					@KHAMCHINH INT,
					@TROKHAM INT = NULL,
					@GHICHU NVARCHAR(255),
					@MAKHDIEUTRI INT OUTPUT
AS
	BEGIN
		IF @TROKHAM IS NOT NULL
			BEGIN
				IF @TROKHAM = @KHAMCHINH
					BEGIN
						RAISERROR('Nha sĩ khám chính không thể trùng với nha sĩ trợ khám!', 16, 1)
						RETURN
					END
			END
		BEGIN TRY
			INSERT INTO KHDIEUTRI VALUES(@MAHSBN,@MADIEUTRI,@MOTAKH, @NGAYDIEUTRI, @KHAMCHINH, @TROKHAM, @GHICHU, 1, NULL)
			SET @MAKHDIEUTRI = SCOPE_IDENTITY()
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END
CREATE OR ALTER PROC SP_CREATERANGDIEUTRI
					@MAKHDIEUTRI INT,
					@MARANG INT,
					@MABEMATRANG INT
AS
	BEGIN
		BEGIN TRY
			INSERT INTO RANGDIEUTRI VALUES(@MAKHDIEUTRI, @MARANG, @MABEMATRANG)
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END

CREATE OR ALTER PROC SP_GET_DATATABLE_KHDIEUTRI
	@FILTERQUERY NVARCHAR(MAX),
	@COLNAME NVARCHAR(MAX),
	@COLSORTORDER NVARCHAR(MAX),
	@OFFSET_START NVARCHAR(MAX),
	@LENGTH NVARCHAR(MAX),
	@MAKH INT
AS
BEGIN
	DECLARE @SQL1 NVARCHAR(MAX)
	DECLARE @SQL2 NVARCHAR(MAX)
	IF (@MAKH IS NOT NULL)
	BEGIN
		SET @SQL1 = 'SELECT COUNT(*) recordsTotal FROM KHDIEUTRI KH JOIN HOSOBN HS ON KH.MAHSBN = HS.MAHSBN WHERE MAKH = ' + CONVERT(VARCHAR(MAX),@MAKH) + ' '
		SET @SQL2 = 'SELECT KH.MAKHDIEUTRI, 
					KH.MAHSBN, HS.HOTENBN, 
					DT.MOTA, 
					KH.NGAYDIEUTRI, 
					KH.KHAMCHINH, NS1.HOTEN NS1, 
					KH.TROKHAM, NS2.HOTEN NS2,
					CASE
						WHEN KH.TRANGTHAI = 1 THEN N"Đang điều trị"
						WHEN KH.TRANGTHAI = 2 THEN N"Đã hoàn thành"
						WHEN KH.TRANGTHAI = 3 THEN N"Đã hủy"
						ELSE "không xác định"
					END AS TRANGTHAI, 
					CASE
						WHEN KH.MAHDTT IS NOT NULL THEN N"Đã trả tiền"
						ELSE N"Chưa trả tiền"
					END AS TRANGTHAI_TIEN,
					MOTAKH, GHICHU
					FROM KHDIEUTRI KH 
					JOIN HOSOBN HS ON KH.MAHSBN = HS.MAHSBN 
					JOIN DIEUTRI DT ON DT.MADIEUTRI = KH.MADIEUTRI 
					JOIN NHASI NS1 ON KH.KHAMCHINH = NS1.MANS 
					JOIN NHASI NS2 ON NS2.MANS = KH.TROKHAM
					WHERE MAKH = ' + CONVERT(VARCHAR(MAX),@MAKH) + ' '

	END
	ELSE
	BEGIN
		SET @SQL1 =  'SELECT COUNT(*) recordsTotal FROM KHDIEUTRI '
		SET @SQL2 = 'SELECT KH.MAKHDIEUTRI, 
					KH.MAHSBN, HS.HOTENBN, 
					DT.MOTA, 
					KH.NGAYDIEUTRI, 
					KH.KHAMCHINH, NS1.HOTEN NS1, 
					KH.TROKHAM, NS2.HOTEN NS2,
					CASE
						WHEN KH.TRANGTHAI = 1 THEN N"Đang điều trị"
						WHEN KH.TRANGTHAI = 2 THEN N"Đã hoàn thành"
						WHEN KH.TRANGTHAI = 3 THEN N"Đã hủy"
						ELSE "không xác định"
					END AS TRANGTHAI, 
					CASE
						WHEN KH.MAHDTT IS NOT NULL THEN N"Đã trả tiền"
						ELSE N"Chưa trả tiền"
					END AS TRANGTHAI_TIEN,
					MOTAKH, GHICHU
					FROM KHDIEUTRI KH 
					JOIN HOSOBN HS ON KH.MAHSBN = HS.MAHSBN 
					JOIN DIEUTRI DT ON DT.MADIEUTRI = KH.MADIEUTRI 
					JOIN NHASI NS1 ON KH.KHAMCHINH = NS1.MANS 
					JOIN NHASI NS2 ON NS2.MANS = KH.TROKHAM'
	END
	EXEC SP_EXECUTESQL @SQL1
	
	SET @SQL1 = @SQL1 + @FILTERQUERY
	EXEC SP_EXECUTESQL @SQL1


	SET @SQL2 = @SQL2 + @FILTERQUERY +
                ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
	EXEC SP_EXECUTESQL @SQL2
END
GO
