use CSDLNC
CREATE OR ALTER PROC SP_GETKHDT
					 @MAKH INT = NULL
AS
	BEGIN
		IF @MAKH IS NULL
			BEGIN
				SELECT * FROM KHDIEUTRI
			END
		ELSE
			BEGIN
				SELECT * FROM KHDIEUTRI WHERE @MAKH = MAKHDIEUTRI
			END
	END
GO
CREATE OR ALTER PROC SP_GETKHDTBASEDONMAHSBN
					 @MAHSBN INT = NULL
AS
	IF @MAHSBN IS NOT NULL
		BEGIN
			SELECT * FROM KHDIEUTRI WHERE @MAHSBN = MAHSBN
		END
GO
CREATE OR ALTER PROC SP_GETDIEUTRI
AS
	SELECT MADIEUTRI, MOTA FROM DIEUTRI
GO

CREATE OR ALTER PROC SP_GETNHASI
AS
	SELECT MANS, HOTEN FROM NHASI
GO

CREATE OR ALTER PROC SP_GETRANG1
AS
	SELECT * FROM RANG
GO

CREATE OR ALTER PROC SP_LISTHSBN
AS
	SELECT * FROM HOSOBN
GO

CREATE OR ALTER PROC SP_LISTBEMATRANG
AS
	SELECT * FROM BEMATRANG
GO