CREATE NONCLUSTERED INDEX IX_HOSOBN_MAKH
ON HOSOBN(MAKH)

CREATE NONCLUSTERED INDEX IX_KHDIEUTRI_MAHSBN_MAHDTT_TRANGTHAI
ON KHDIEUTRI(MAHSBN, MAHDTT, TRANGTHAI)
INCLUDE(NGAYDIEUTRI, TONGTIEN)


CREATE NONCLUSTERED INDEX IX_KHDIEUTRI_MAHDTT_TRANGTHAI
ON KHDIEUTRI(MAHDTT, TRANGTHAI)
INCLUDE(NGAYDIEUTRI, TONGTIEN, MAHSBN)

CREATE NONCLUSTERED INDEX IX_THUOC_TENTHUOC
ON THUOC(TENTHUOC)
INCLUDE(MATHUOC,CONGDUNG,CHONGCHIDINH,TACDUNGPHU,HDSD,HSD,NSX,DONGIA,SL)

CREATE NONCLUSTERED INDEX IX_THUOC_CONGDUNG
ON THUOC(CONGDUNG)
INCLUDE(MATHUOC,TENTHUOC,CHONGCHIDINH,TACDUNGPHU,HDSD,HSD,NSX,DONGIA,SL)

CREATE NONCLUSTERED INDEX IX_THUOC_TENTHUOC_CONGDUNG
ON THUOC(TENTHUOC,CONGDUNG)
INCLUDE(MATHUOC,CHONGCHIDINH,TACDUNGPHU,HDSD,HSD,NSX,DONGIA,SL)