CREATE OR ALTER PROC SP_GET_LIST_THUOC
AS
	SELECT * FROM THUOC
GO

CREATE OR ALTER PROC SP_POST_CREATE_THUOC
	@TENTHUOC NVARCHAR(255),
	@CONGDUNG NVARCHAR(255),
	@CHONGCHIDINH NVARCHAR(255),
	@TACDUNGPHU NVARCHAR(255),
	@HDSD NVARCHAR(255),
	@HSD DATE,
	@NSX NVARCHAR(255),
	@DONGIA INT,
	@SL INT
AS
	IF @DONGIA < 0
	BEGIN
		RAISERROR(N'Đơn giá phải là một số dương', 16, 1)
		RETURN
	END
	IF @SL < 0
	BEGIN
		RAISERROR(N'Số lượng phải là một số dương', 16, 1)
		RETURN
	END
	IF DATEDIFF(DAY, GETDATE(), @HSD) < 0
	BEGIN
		RAISERROR(N'HSD không được bé hơn ngày hiện tại', 16, 1)
		RETURN
	END
	BEGIN TRY
		INSERT INTO THUOC
		VALUES (@TENTHUOC,@CONGDUNG,@CHONGCHIDINH,@TACDUNGPHU,@HDSD,@HSD,@NSX,@DONGIA,@SL)
		PRINT N'Thêm thuốc thành công'
		RETURN
	END TRY
	BEGIN CATCH
		RAISERROR(N'Lỗi hệ thống', 16, 1)
	END CATCH
GO

CREATE OR ALTER PROC SP_POST_UPDATE_THUOC
	@MATHUOC INT,
	@TENTHUOC NVARCHAR(255),
	@CONGDUNG NVARCHAR(255),
	@CHONGCHIDINH NVARCHAR(255),
	@TACDUNGPHU NVARCHAR(255),
	@HDSD NVARCHAR(255),
	@HSD DATE,
	@NSX NVARCHAR(255),
	@DONGIA INT,
	@SL INT
AS
	IF @DONGIA < 0
	BEGIN
		RAISERROR(N'Đơn giá phải là một số dương', 16, 1)
		RETURN
	END
	IF DATEDIFF(DAY, GETDATE(), @HSD) < 0
	BEGIN
		RAISERROR(N'HSD không được bé hơn ngày hiện tại', 16, 1)
		RETURN
	END
	BEGIN TRY
		UPDATE THUOC
		SET TENTHUOC = @TENTHUOC,
			CONGDUNG = @CONGDUNG,
			CHONGCHIDINH = @CHONGCHIDINH,
			TACDUNGPHU = @TACDUNGPHU,
			HDSD = @HDSD,
			HSD = @HSD,
			NSX = @NSX,
			DONGIA = @DONGIA,
			SL = @SL
		WHERE MATHUOC = @MATHUOC
		PRINT N'Cập nhật thuốc thành công'
		RETURN
	END TRY
	BEGIN CATCH
		RAISERROR(N'Lỗi hệ thống', 16, 1)
	END CATCH
GO
