CREATE NONCLUSTERED INDEX IX_HOSOBN_MAKH
ON HOSOBN(MAKH)

CREATE NONCLUSTERED INDEX IX_KHDIEUTRI_MAHSBN_MAHDTT_TRANGTHAI
ON KHDIEUTRI(MAHSBN, MAHDTT, TRANGTHAI)
INCLUDE(NGAYDIEUTRI, TONGTIEN)


CREATE NONCLUSTERED INDEX IX_KHDIEUTRI_MAHDTT_TRANGTHAI
ON KHDIEUTRI(MAHDTT, TRANGTHAI)
INCLUDE(NGAYDIEUTRI, TONGTIEN, MAHSBN)