--DECLARE @ERROR_MESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
--RAISERROR(@ERROR_MESSAGE, 16, 1)

CREATE OR ALTER PROC SP_GET_DATATABLE_THUOC
	@FILTERQUERY NVARCHAR(MAX),
	@COLNAME NVARCHAR(MAX),
	@COLSORTORDER NVARCHAR(MAX),
	@OFFSET_START NVARCHAR(MAX),
	@LENGTH NVARCHAR(MAX)
AS
BEGIN
BEGIN TRY
	DECLARE @SQL NVARCHAR(MAX) = N'SELECT COUNT(*) recordsTotal FROM THUOC '
	EXEC SP_EXECUTESQL @SQL
	
	SET @SQL = @SQL + @FILTERQUERY
	EXEC SP_EXECUTESQL @SQL

	SET @SQL = 'SELECT * FROM THUOC ' + @FILTERQUERY +
                    ' ORDER BY ' + @COLNAME + ' ' + @COLSORTORDER +
                    ' OFFSET ' + @OFFSET_START + ' ROWS FETCH NEXT ' + @LENGTH + ' ROWS ONLY;';
	EXEC SP_EXECUTESQL @SQL
END TRY
BEGIN CATCH
	DECLARE @ERROR_MESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
	RAISERROR(@ERROR_MESSAGE, 16, 1)
END CATCH
END
GO

CREATE OR ALTER PROC SP_POST_CREATE_THUOC
	@TENTHUOC NVARCHAR(255),
	@CONGDUNG NVARCHAR(255),
	@CHONGCHIDINH NVARCHAR(255),
	@TACDUNGPHU NVARCHAR(255),
	@HDSD NVARCHAR(255),
	@HSD DATE,
	@NSX NVARCHAR(255),
	@DONGIA INT,
	@SL INT
AS
	IF @DONGIA < 0
	BEGIN
		RAISERROR(N'Đơn giá phải là một số dương', 16, 1)
		RETURN
	END
	IF @SL < 0
	BEGIN
		RAISERROR(N'Số lượng phải là một số dương', 16, 1)
		RETURN
	END
	IF DATEDIFF(DAY, GETDATE(), @HSD) < 0
	BEGIN
		RAISERROR(N'HSD không được bé hơn ngày hiện tại', 16, 1)
		RETURN
	END
	BEGIN TRY
		INSERT INTO THUOC
		VALUES (@TENTHUOC,@CONGDUNG,@CHONGCHIDINH,@TACDUNGPHU,@HDSD,@HSD,@NSX,@DONGIA,@SL)
		PRINT N'Thêm thuốc thành công'
		RETURN
	END TRY
	BEGIN CATCH
		RAISERROR(N'Lỗi hệ thống', 16, 1)
	END CATCH
GO

CREATE OR ALTER PROC SP_POST_UPDATE_THUOC
	@MATHUOC INT,
	@TENTHUOC NVARCHAR(255),
	@CONGDUNG NVARCHAR(255),
	@CHONGCHIDINH NVARCHAR(255),
	@TACDUNGPHU NVARCHAR(255),
	@HDSD NVARCHAR(255),
	@HSD DATE,
	@NSX NVARCHAR(255),
	@DONGIA INT,
	@SL INT
AS
	IF @DONGIA < 0
	BEGIN
		RAISERROR(N'Đơn giá phải là một số dương', 16, 1)
		RETURN
	END
	IF DATEDIFF(DAY, GETDATE(), @HSD) < 0
	BEGIN
		RAISERROR(N'HSD không được bé hơn ngày hiện tại', 16, 1)
		RETURN
	END
	BEGIN TRY
		UPDATE THUOC
		SET TENTHUOC = @TENTHUOC,
			CONGDUNG = @CONGDUNG,
			CHONGCHIDINH = @CHONGCHIDINH,
			TACDUNGPHU = @TACDUNGPHU,
			HDSD = @HDSD,
			HSD = @HSD,
			NSX = @NSX,
			DONGIA = @DONGIA,
			SL = @SL
		WHERE MATHUOC = @MATHUOC
		PRINT N'Cập nhật thuốc thành công'
		RETURN
	END TRY
	BEGIN CATCH
		RAISERROR(N'Lỗi hệ thống', 16, 1)
	END CATCH
GO
