CREATE OR ALTER PROC SP_POST_UPDATE_THUOC_T1
	@MATHUOC INT,
	@TENTHUOC NVARCHAR(255),
	@CONGDUNG NVARCHAR(255),
	@CHONGCHIDINH NVARCHAR(255),
	@TACDUNGPHU NVARCHAR(255),
	@HDSD NVARCHAR(255),
	@HSD DATE,
	@NSX NVARCHAR(255),
	@DONGIA INT,
	@SL INT
AS
SET TRAN ISOLATION LEVEL READ COMMITTED 
BEGIN TRAN
BEGIN TRY
	IF NOT EXISTS (SELECT 1 FROM THUOC WITH (UPDLOCK) WHERE MATHUOC = @MATHUOC)
		RAISERROR(N'Thuốc không tồn tại', 16, 1)
	IF @DONGIA < 0
		RAISERROR(N'Đơn giá phải là một số dương', 16, 1)
	
	IF DATEDIFF(DAY, GETDATE(), @HSD) < 0
		RAISERROR(N'HSD không được bé hơn ngày hiện tại', 16, 1)
	WAITFOR DELAY '0:0:05'

	UPDATE THUOC
	SET TENTHUOC = @TENTHUOC,
		CONGDUNG = @CONGDUNG,
		CHONGCHIDINH = @CHONGCHIDINH,
		TACDUNGPHU = @TACDUNGPHU,
		HDSD = @HDSD,
		HSD = @HSD,
		NSX = @NSX,
		DONGIA = @DONGIA,
		SL = @SL
	WHERE MATHUOC = @MATHUOC
	PRINT N'Cập nhật thuốc thành công'
	
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0  
		ROLLBACK TRAN
	DECLARE @ERROR_MESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
	RAISERROR(@ERROR_MESSAGE, 16, 1)
	RETURN
END CATCH
COMMIT TRAN
GO

CREATE OR ALTER PROC SP_POST_UPDATE_THUOC_T2
	@MATHUOC INT,
	@TENTHUOC NVARCHAR(255),
	@CONGDUNG NVARCHAR(255),
	@CHONGCHIDINH NVARCHAR(255),
	@TACDUNGPHU NVARCHAR(255),
	@HDSD NVARCHAR(255),
	@HSD DATE,
	@NSX NVARCHAR(255),
	@DONGIA INT,
	@SL INT
AS
SET TRAN ISOLATION LEVEL READ COMMITTED 
BEGIN TRAN
BEGIN TRY
	IF NOT EXISTS (SELECT 1 FROM THUOC WITH (UPDLOCK) WHERE MATHUOC = @MATHUOC)
		RAISERROR(N'Thuốc không tồn tại', 16, 1)
	IF @DONGIA < 0
		RAISERROR(N'Đơn giá phải là một số dương', 16, 1)

	WAITFOR DELAY '0:0:05'
	
	IF DATEDIFF(DAY, GETDATE(), @HSD) < 0
		RAISERROR(N'HSD không được bé hơn ngày hiện tại', 16, 1)
	
	UPDATE THUOC
	SET TENTHUOC = @TENTHUOC,
		CONGDUNG = @CONGDUNG,
		CHONGCHIDINH = @CHONGCHIDINH,
		TACDUNGPHU = @TACDUNGPHU,
		HDSD = @HDSD,
		HSD = @HSD,
		NSX = @NSX,
		DONGIA = @DONGIA,
		SL = @SL
	WHERE MATHUOC = @MATHUOC
	PRINT N'Cập nhật thuốc thành công'
	
END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0  
		ROLLBACK TRAN
	DECLARE @ERROR_MESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
	RAISERROR(@ERROR_MESSAGE, 16, 1)
	RETURN
END CATCH
COMMIT TRAN
GO
