--CREATE TYPE THUOCARRAY AS TABLE
--(
--	MATHUOC INT,
--	SOLUONG INT
--)
--go
CREATE OR ALTER PROC SP_ADD_CHI_TIET_DON_THUOC
	@MAKHDIEUTRI INT,
	@GHICHU NVARCHAR(255),
	@MANGTHUOC THUOCARRAY READONLY
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
			IF EXISTS (SELECT 1 FROM DONTHUOC WHERE MAKHDIEUTRI = @MAKHDIEUTRI) OR EXISTS (SELECT 1 FROM CHITIET_DONTHUOC WHERE MAKHDIEUTRI = @MAKHDIEUTRI)		
			BEGIN
				RAISERROR('Kế hoạch điều trị này đã được kê đơn thuốc và không thể tạo thêm!', 16, 1)
				RETURN
			END
			EXEC SP_ADD_DON_THUOC @MAKHDIEUTRI,@GHICHU

			INSERT INTO CHITIET_DONTHUOC (MAKHDIEUTRI, MATHUOC, SOLUONG, DONGIATHUOC)
			SELECT @MAKHDIEUTRI, M.MATHUOC, M.SOLUONG, THUOC.DONGIA
			FROM @MANGTHUOC AS M
			JOIN THUOC ON M.MATHUOC = THUOC.MATHUOC;

			CREATE TABLE #TempSLTHUOC (
				MATHUOC INT,
				SOLUONG INT
			)

			-- Chèn dữ liệu từ biến kiểu bảng @SLTHUOC vào bảng tạm
			INSERT INTO #TempSLTHUOC (MATHUOC, SOLUONG)
			SELECT T.MATHUOC, T.SL
			FROM THUOC AS T
			INNER JOIN @MANGTHUOC AS M ON T.MATHUOC = M.MATHUOC

			WAITFOR DELAY '00:00:05'

			UPDATE THUOC
			SET SL = T.SOLUONG - M.SOLUONG
			FROM @MANGTHUOC AS M
			JOIN THUOC ON M.MATHUOC = THUOC.MATHUOC
			JOIN #TempSLTHUOC AS T ON T.MATHUOC = THUOC.MATHUOC

			EXEC SP_UPDATEDONTHUOC @MAKHDIEUTRI

			EXEC SP_UPDATETRANGTHAI 2 ,@MAKHDIEUTRI

			UPDATE KHDIEUTRI
			SET TONGTIEN = (SELECT SUM(TONGTIENTHUOC) FROM DONTHUOC WHERE @MAKHDIEUTRI = MAKHDIEUTRI) + (SELECT PHIDIEUTRI FROM DIEUTRI JOIN KHDIEUTRI ON DIEUTRI.MADIEUTRI = KHDIEUTRI.MADIEUTRI WHERE MAKHDIEUTRI = @MAKHDIEUTRI)
			WHERE @MAKHDIEUTRI = MAKHDIEUTRI

			DECLARE @MAHSBN INT = (SELECT TOP 1 MAHSBN FROM KHDIEUTRI WHERE MAKHDIEUTRI = @MAKHDIEUTRI)

			UPDATE HOSOBN
			SET TONGTIENDIEUTRI = (SELECT SUM(TONGTIEN) FROM KHDIEUTRI WHERE MAHSBN = @MAHSBN AND TRANGTHAI = 2)
			WHERE MAHSBN = @MAHSBN
			IF (EXISTS (SELECT 1 FROM @MANGTHUOC MT JOIN THUOC T ON MT.MATHUOC = T.MATHUOC WHERE MT.SOLUONG > T.SL))
			BEGIN
				RAISERROR('Số lượng để kê đơn vượt qua số còn lại trong kho!', 16, 1)
				RETURN
			END
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;

		SELECT @ErrorMessage = ERROR_MESSAGE(), 
			   @ErrorSeverity = ERROR_SEVERITY(),
			   @ErrorState = ERROR_STATE();
		RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
	END CATCH
END
GO

CREATE OR ALTER  PROC SP_UPDATEDONTHUOC
					@MAKHDIEUTRI INT
AS
	BEGIN
		BEGIN TRY
			UPDATE DONTHUOC
			SET TONGTIENTHUOC = (SELECT SUM(SOLUONG*DONGIATHUOC) FROM CHITIET_DONTHUOC CT WHERE CT.MAKHDIEUTRI = @MAKHDIEUTRI)
			WHERE DONTHUOC.MAKHDIEUTRI = @MAKHDIEUTRI;
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END
GO

CREATE OR ALTER PROC SP_UPDATETRANGTHAI
					@TRANGTHAI INT,
					@MAKHDIEUTRI INT
AS
	BEGIN
		BEGIN TRY
			UPDATE KHDIEUTRI
			SET TRANGTHAI = @TRANGTHAI
			WHERE MAKHDIEUTRI = @MAKHDIEUTRI
			IF @TRANGTHAI = 3
				BEGIN
					DECLARE @MAHSBN INT = (SELECT MAHSBN FROM KHDIEUTRI WHERE MAKHDIEUTRI = @MAKHDIEUTRI)
					PRINT(@MAHSBN)
					UPDATE HOSOBN
					SET TONGTIENDIEUTRI = TONGTIENDIEUTRI - (SELECT TONGTIEN FROM KHDIEUTRI WHERE MAKHDIEUTRI = @MAKHDIEUTRI)
					WHERE MAHSBN = @MAHSBN
				END
		END TRY
		BEGIN CATCH
			RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
		END CATCH
	END
GO


CREATE OR ALTER  PROC SP_ADD_DON_THUOC
	@MAKHDIEUTRI INT,
	@GHICHU NVARCHAR(255)
AS
BEGIN
	BEGIN TRY
		INSERT INTO DONTHUOC VALUES(@MAKHDIEUTRI,GETDATE(),1,@GHICHU)
	END TRY
	BEGIN CATCH
		RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
	END CATCH
END
Go

CREATE OR ALTER PROC SP_XEM_DON_THUOC
	@MAKHDIEUTRI INT
AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
			SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
			SELECT T.TENTHUOC, CT.SOLUONG, CT.DONGIATHUOC FROM CHITIET_DONTHUOC CT JOIN THUOC T ON CT.MATHUOC = T.MATHUOC WHERE @MAKHDIEUTRI = MAKHDIEUTRI
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		RAISERROR('Lỗi hệ thống hoặc lỗi khoá ngoại!', 16, 1)
	END CATCH
END
GO