-- QTV04
CREATE OR ALTER PROC SP_UPDATE_LICHLAMVIEC
	@MANS INT,
	@NEWLLV TMPLICHLAMVIEC READONLY
AS
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
	BEGIN TRY
		DELETE FROM LICHLAMVIEC
		WHERE MANS = @MANS

		--------------------------
		WAITFOR DELAY '0:0:05'
		--------------------------

		INSERT INTO LICHLAMVIEC (MANS, NGAYLAM, GIOBATDAU, GIOKETTHUC)
		SELECT MANS, NGAYLAM, CONVERT(TIME, GIOBATDAU) AS GIOBATDAU, CONVERT(TIME, GIOKETTHUC) AS GIOKETTHUC
		FROM @NEWLLV
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		IF CHARINDEX('CK_LICHLAMVIEC_GIOBATDAU', @ErrorMessage) > 0
		BEGIN
			RAISERROR('Giờ bắt đầu làm phải từ 8 giờ sáng!', 16, 1)
		END
		ELSE IF CHARINDEX('CK_LICHLAMVIEC_GIOKETTHUC', @ErrorMessage) > 0
		BEGIN
			RAISERROR('Giờ tan ca phải từ trước 20h!', 16, 1)
		END
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

--NS02
CREATE OR ALTER PROC SP_GET_LLV_WEEKLY
	@MANS INT,
	@STARTDATE DATE,
	@ENDDATE DATE
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	WITH CONVERTEDDATE (NGAYNGHI) AS
	(
		SELECT DATEPART(WEEKDAY, LN.NGAYNGHI) NGAYNGHI
		FROM LICHNGHI LN
		WHERE LN.MANS = @MANS 
		AND @STARTDATE <= LN.NGAYNGHI AND LN.NGAYNGHI <= @ENDDATE
	)
	SELECT LLV.NGAYLAM, DATEPART(HOUR, GIOBATDAU) BATDAU, DATEPART(HOUR, GIOKETTHUC) KETTHUC
	FROM LICHLAMVIEC AS LLV
	LEFT JOIN CONVERTEDDATE LN ON LLV.NGAYLAM = LN.NGAYNGHI
	WHERE LLV.MANS = @MANS
	AND LN.NGAYNGHI IS NULL;
COMMIT TRAN
GO


-- MONTH
CREATE OR ALTER PROC SP_GET_LLV_MONTHLY
	@MANS INT,
	@STARTDATE DATE,
	@ENDDATE DATE
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
	DECLARE @MONTH INT = MONTH(@STARTDATE)
	DECLARE @YEAR INT = YEAR(@STARTDATE);

	WITH NUMBERS (VAL) AS
	(
		SELECT 1 AS VAL
		UNION ALL
		SELECT VAL + 1 FROM NUMBERS
		WHERE VAL + 1 <= DAY(EOMONTH(DATEFROMPARTS(@YEAR,@MONTH,1)))
	),
	CONVERTEDDATE (NGAY) AS
	(
		SELECT DATEFROMPARTS(@YEAR,@MONTH,NUMBERS.VAL) AS NGAY
		FROM NUMBERS
	),
	CONVERTEDLICHNGHI (NGAY) AS
	(
		SELECT NGAYNGHI NGAY
		FROM LICHNGHI LN
		WHERE LN.MANS = @MANS 
		AND @STARTDATE <= LN.NGAYNGHI AND LN.NGAYNGHI <= @ENDDATE
	),
	CONVERTEDLICHLAM (NGAY) AS
	(
		SELECT CD.NGAY
		FROM CONVERTEDDATE CD
		LEFT JOIN CONVERTEDLICHNGHI CLN ON CD.NGAY = CLN.NGAY
		WHERE CLN.NGAY IS NULL
	)
	SELECT DATEPART(DAY, CV.NGAY) NGAYLAM, DATEPART(HOUR, GIOBATDAU) BATDAU, DATEPART(HOUR, GIOKETTHUC) KETTHUC
	FROM LICHLAMVIEC AS LLV
	JOIN CONVERTEDLICHLAM CV ON LLV.NGAYLAM = DATEPART(WEEKDAY, CV.NGAY)
	WHERE LLV.MANS = @MANS
COMMIT
GO