-- ALL01
CREATE OR ALTER PROC SP_LOGIN_KHACHHANG
	@SDT CHAR(10),
	@MATKHAU VARCHAR(50),
	@LOAITK INT,
	@ID INT = NULL OUTPUT,
	@HOTEN NVARCHAR(255) = NULL OUTPUT,
	@LOAINV BIT = NULL OUTPUT
AS
SET TRAN ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
	IF @LOAITK = 1
	BEGIN
		IF EXISTS (
			SELECT 1
			FROM KHACHHANG
			WHERE SDT = @SDT
		)
		BEGIN
			IF EXISTS (
				SELECT 1
				FROM KHACHHANG
				WHERE SDT = @SDT AND MATKHAU = @MATKHAU
			)
			BEGIN
				----------------------
				WAITFOR DELAY '0:0:05'
				----------------------
				SELECT @ID = MAKH, @HOTEN = HOTEN
				FROM KHACHHANG
				WHERE SDT = @SDT AND MATKHAU = @MATKHAU
				--PRINT N'Đăng nhập thành công'
				SET @LOAINV = 0
				COMMIT TRAN
				RETURN
			END
		END
	END
	ELSE IF @LOAITK = 2
	BEGIN
		IF EXISTS (
			SELECT 1
			FROM NHASI
			WHERE SDT = @SDT
		)
		BEGIN
			IF EXISTS (
				SELECT 1
				FROM NHASI
				WHERE SDT = @SDT AND MATKHAU = @MATKHAU
			)
			BEGIN
				EXEC SP_SHOW_LOCK_IN_DB
				----------------------
				WAITFOR DELAY '0:0:05'
				----------------------
				SELECT @ID = MANS, @HOTEN = HOTEN
				FROM NHASI
				WHERE SDT = @SDT AND MATKHAU = @MATKHAU
				--PRINT N'Đăng nhập thành công'
				SET @LOAINV = 0
				COMMIT TRAN
				RETURN
			END
		END
	END
	ELSE IF @LOAITK = 3
	BEGIN
		IF EXISTS (
			SELECT 1
			FROM NVNGHIEPVU
			WHERE SDT = @SDT
		)
		BEGIN
			IF EXISTS (
				SELECT 1
				FROM NVNGHIEPVU
				WHERE SDT = @SDT AND MATKHAU = @MATKHAU
			)
			BEGIN
				----------------------
				WAITFOR DELAY '0:0:05'
				----------------------
				SELECT @ID = MANV, @HOTEN = HOTEN, @LOAINV = LOAINV
				FROM NVNGHIEPVU
				WHERE SDT = @SDT AND MATKHAU = @MATKHAU
				--PRINT N'Đăng nhập thành công'
				COMMIT TRAN
				RETURN
			END
		END
	END
	BEGIN
		RAISERROR('Số điện thoại hoặc mật khẩu không chính xác', 16, 1)
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
GO



-- QTV02

-- UPDATE NHASI
CREATE OR ALTER PROC SP_UPDATE_NHASI
	@MANS INT,
	@HOTEN NVARCHAR(255),
	@NGAYSINH DATE,
	@GIOITINH NVARCHAR(10),
	@DIACHI NVARCHAR(255),
	@MATKHAU VARCHAR(50)
AS
BEGIN TRAN
	BEGIN TRY
		UPDATE NHASI
		SET
			HOTEN = @HOTEN,
			NGAYSINH = @NGAYSINH,
			GIOITINH = @GIOITINH,
			DIACHI = @DIACHI,
			MATKHAU = @MATKHAU
		WHERE MANS = @MANS

	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO


-- UPDATE NHANVIEN
CREATE OR ALTER PROC SP_UPDATE_NHANVIEN
	@MANV INT,
	@HOTEN NVARCHAR(255),
	@NGAYSINH DATE,
    @GIOITINH NVARCHAR(10),	
    @DIACHI NVARCHAR(255),
	@LOAINV BIT,
	@MATKHAU VARCHAR(50)
AS
BEGIN TRAN
	BEGIN TRY
		UPDATE NVNGHIEPVU
		SET
			HOTEN = @HOTEN,
			NGAYSINH = @NGAYSINH,
            GIOITINH = @GIOITINH,
			DIACHI = @DIACHI,
			LOAINV = @LOAINV,
			MATKHAU = @MATKHAU
		WHERE MANV = @MANV
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(MAX) = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1)
		ROLLBACK TRAN
		RETURN
	END CATCH
COMMIT TRAN
GO

